<?php
$thang_options = range(1, 12);
$nam_options = array();
for ($i = 1900; $i <= 2050; $i++) {
    $nam_options[$i] = $i;
}
?>

<div id="dv_form_nghi_huu">

    <?php if (sizeof($this->error_message)): ?>
        <div class="alert alert-error" id="dv_he_so_error">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h5>Thông báo!</h5>
            Cập nhật không thành công vì:
            <ol>
                <?php foreach ($this->error_message as $message): ?>
                    <li><?php echo $message; ?></li>
                <?php endforeach; ?>
            </ol>
        </div>
    <?php endif; ?>
    <?php if ($this->success_message): ?>
        <div class="alert alert-success" id="dv_he_so_success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h5>Thông báo!</h5>
            Duyệt nghỉ hưu thành công.
        </div>
    <?php endif; ?>


    <form class="form-horizontal" id="fr_nghi_huu">
        <input type="hidden" id="nh_em_id" value="<?php echo $this->em_id; ?>"/>
        <div class="control-group">
            <label class="control-label">Họ tên:</label>
            <div class="controls">
                <strong>
                    <?php
                    echo $this->employee_info->em_ho . ' ' . $this->employee_info->em_ten
                    ?> 
                </strong>
            </div>
        </div> 

        <div class="control-group">
            <label class="control-label">Ngày sinh:</label>
            <div class="controls">
                <strong>
                    <?php
                    echo date('d/m/Y', strtotime($this->employee_info->em_ngay_sinh));
                    ?> 
                </strong>
            </div>
        </div> 

        <div class="control-group">
            <label class="control-label" for="em_chuc_vu">Chức vụ</label>
            <div class="controls">
                <strong>
                    <?php
                    $chuc_vu_options = array(0 => '');
                    foreach ($this->list_chuc_vu as $chuc_vu) {
                        $chuc_vu_options[$chuc_vu->cv_id] = $chuc_vu->cv_name;
                    }
                    echo $chuc_vu_options[$this->employee_info->em_chuc_vu];
                    ?> 
                </strong>
            </div>
        </div> 

        <div class="control-group">
            <label class="control-label" for="em_phong_ban">Đơn vị</label>
            <div class="controls">
                <strong>
                    <?php
                    $phong_ban_options = array(0 => '');
                    foreach ($this->list_phong_ban as $phong_ban) {
                        $phong_ban_options[$phong_ban->pb_id] = $phong_ban->pb_name;
                    }
                    echo $phong_ban_options[$this->employee_info->em_phong_ban];
                    ?> 
                </strong>
            </div>
        </div> 

    </form>
</div>