<?php
$list_phong_ban = array();
foreach ($this->list_phong_ban as $phong_ban) {
    $list_phong_ban[$phong_ban->pb_id] = $phong_ban->pb_name;
}

$list_phong_ban_options = array('0' => 'Chọn phòng ban');
foreach ($this->list_phong_ban_option as $phong_ban) {
    $list_phong_ban_options[$phong_ban->pb_id] = $phong_ban->pb_name;
}
?>
<h5>Duyệt chấm công</h5>               

<div class="main-content-box">  
    <form name="appForm" class="form-horizontal" method="post" action="">
        <div class="control-group">
            <label class="control-label">Phòng ban</label>
            <div class="controls">
                <?php
                echo $this->formSelect('sl_phong_ban', $this->pb_id, array('onchange' => 'on_choose_phong_ban()'), $list_phong_ban_options);
                ?>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Tháng</label>
            <div class="controls">
                <div class="input-append">
                    <input class="span2" value="<?php echo $this->thang . '/' . $this->nam; ?>" id="txt_thang_nam" type="text" readonly="true"/>
                    <button class="btn" type="button" id="btn_chon_thang">Chọn tháng!</button>
                </div>
            </div>
        </div>
        <div class="clearfix">
        </div>
        <div class="btn-toolbar float_left">
            <div class="btn-group">
                <button class="btn" onclick="OnSubmitForm('<?php echo $this->baseUrl('tochuccanbo/duyetchamcong/updatestatus/status/1/thang/' . $this->thang . '/nam/' . $this->nam . '/phongban/' . $this->pb_id); ?>')"><i class="icon-ok-sign"></i> Duyệt</button>
                <button class="btn" onclick="OnSubmitForm('<?php echo $this->baseUrl('tochuccanbo/duyetchamcong/updatestatus/status/0/thang/' . $this->thang . '/nam/' . $this->nam . '/phongban/' . $this->pb_id); ?>')"><i class="icon-remove-sign"></i> Không duyệt</button>
            </div>
        </div>

        <div class="clearfix">
        </div>
        <?php $days_in_month = cal_days_in_month(0, (int) $this->thang, (int) $this->nam); ?>
        <table class="table table-bordered table-thong-ke-thang">
            <thead>

                <tr> 
                    <th class="checkall_style" rowspan="2"><input type="checkbox" name="check_all" id="checkbox" onclick="checkedAll()"></th>
                    <th style="width: 150px;vertical-align:inherit" rowspan="2">Họ tên</th>
                    <th colspan="<?php echo $days_in_month ?>" style="text-align: center">Ngày công trong tháng</th>
                    <th style="width: 50px;vertical-align:inherit" colspan="3">Giờ làm thêm</th>
                </tr>
                <tr>
                    <?php for ($i = 1; $i <= $days_in_month; $i++) { ?>                    
                        <th style="width: 5px;" <?php $this->viewCheckChuNhatThuBay($i, (int) $this->thang, (int) $this->nam); ?>><?php echo $i ?></th>
                    <?php } ?>
                    <th>Số giờ của ngày làm việc</th>
                    <th>Số giờ của ngày thứ 7,CN</th>
                    <th>Số giờ của ngày lễ tết</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->list_nhan_vien as $key => $nv) {
                    $so_gio_lam_le_tet = $so_phut_lam_le_tet = 0;
                    $so_gio_lam_thu_7_cn = $so_phut_lam_thu_7_cn = 0;
                    $view_get_chamcong = $this->viewGetChamCong($nv['em_id'], $this->thang, $this->nam);

                    $class = '';

                    if ($view_get_chamcong->c_ptccb_status > 0) {
                        $class = 'success';
                    } else if ($view_get_chamcong->c_don_vi_status > 0) {
                        $class = 'warning';
                    }
                    ?>
                    <tr>       
                        <td class="checkall_style"><input type="checkbox" name="cid[]" id="cid" value="<?php echo $nv['em_id']; ?>"></td>
                        <td class="<?php echo $class; ?>"><?php echo $nv['em_ho'] . ' ' . $nv['em_ten_dem'] . ' ' . $nv['em_ten'] ?></td>
                        <?php for ($i = 1; $i <= $days_in_month; $i++) { ?>
                            <?php
                            $ngay_chamcong = 'c_ngay_' . $i;
                            $trangthai_ngaycong = $view_get_chamcong->$ngay_chamcong;
                            $check_gio_lam_them = $this->viewGetGioLamThem($nv['em_id'], $i, $this->thang, $this->nam);
                            if ($check_gio_lam_them) {
                                if ($this->viewCheckLeTet($i, $this->thang, $this->nam)) {
                                    $so_gio_lam_le_tet+=$check_gio_lam_them['gio'];
                                    $so_phut_lam_le_tet+=$check_gio_lam_them['phut'];
                                } elseif ($this->viewCheckChuNhatThuBay($i, (int) $this->thang, (int) $this->nam)) {
                                    $so_gio_lam_thu_7_cn+=$check_gio_lam_them['gio'];
                                    $so_phut_lam_thu_7_cn+=$check_gio_lam_them['phut'];
                                }
                            }
                            ?>
                            <td style="width: 10px;" <?php echo $this->viewCheckChuNhatThuBay($i, (int) $this->thang, (int) $this->nam); ?>><?php echo!empty($this->listHoliday[$trangthai_ngaycong]) ? $this->listHoliday[$trangthai_ngaycong]['code'] : '' ?></td>
                            <?php
                        }

                        $doi_gio_thu_7 = floor($so_phut_lam_thu_7_cn / 60);
                        $so_phut_lam_thu_7_cn = $so_phut_lam_thu_7_cn % 60;
                        $so_gio_lam_thu_7_cn += $doi_gio_thu_7;

                        $doi_gio_le_tet = floor($so_phut_lam_le_tet / 60);
                        $so_phut_lam_le_tet = $so_phut_lam_le_tet % 60;
                        $so_gio_lam_le_tet += $doi_gio_le_tet;
                        ?>
                        <td></td>
                        <td><?php echo $so_gio_lam_thu_7_cn . ':' . $so_phut_lam_thu_7_cn; ?></td>
                        <td><?php echo $so_gio_lam_le_tet . ':' . $so_phut_lam_le_tet; ?></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>

        <table class="table">            
            <tbody>
                <tr class="success">
                    <td>Tên mầu xanh - Đã duyệt</td>
                </tr>                
                <tr class="warning">
                    <td>Tên mầu vàng nhạt - Chờ duyệt</td>
                </tr>
                <tr>
                    <td>Tên mầu trắng - Đơn vị chưa duyệt</td>
                </tr>
            </tbody>
        </table>
    </form>
</div>


<script>
    var currentYear = <?php echo $this->nam; ?>;    
    var options = {
        pattern: 'mm/yyyy', // Default is 'mm/yyyy' and separator char is not mandatory 
        startYear: 2013,
        selectedYear: currentYear,
        monthNames: ['Tháng 1', 'Tháng 2', 'Tháng 3', 'Tháng 4', 'Tháng 5', 'Tháng 6', 'Tháng 7', 'Tháng 8', 'Tháng 9', 'Tháng 10', 'Tháng 11', 'Tháng 12']
    };

    var phong_ban = $('#sl_phong_ban').val();
    $('#txt_thang_nam').monthpicker(options);

    $('#txt_thang_nam').monthpicker().bind('monthpicker-click-month', function (e, month, year) { 
        window.location = site_url+'/tochuccanbo/duyetchamcong/index/thang/'+month+'/nam/'+year+'/phongban/'+phong_ban;
    });

    $('#btn_chon_thang').bind('click', function () {
        $('#txt_thang_nam').monthpicker('show');
    });
    
    function on_choose_phong_ban(){
        var phong_ban = $('#sl_phong_ban').val();
        var c_date = $('#txt_thang_nam').val();
        var date_array = c_date.split("/");
        var d = new Date(),
        c_m = d.getMonth(),
        c_y = d.getFullYear();
        if(date_array.length==2 && $.isNumeric(date_array[0]) && $.isNumeric(date_array[1])){
            c_m = date_array[0];
            c_y = date_array[1];
        }        
        window.location = site_url+'/tochuccanbo/duyetchamcong/index/thang/'+c_m+'/nam/'+c_y+'/phongban/'+phong_ban;
    }
    function loadFormChiTiet(em_id, thang, nam, em_name){
        $('#myDetailLabel').html(em_name);       
        $('#mdDetailBody').html('Đang tải dữ liệu');
        $('#mdDetailBody').load(site_url+'/tochuccanbo/duyetchamcong/detail/thang/'+thang+'/nam/'+nam+'/em/'+em_id+' #dv_cham_cong_chi_tiet', function(){
         
        });
    }
    
    function loadFormThongBao(em_id, em_name){        
        $('#mdThongBaoBody #tb_cap_nhat_id').val(em_id);
        $('#mdThongBaoBody #tb_can_bo').html('<strong>'+em_name+'</strong>');
        tinyMCE.get('tb_noi_dung').setContent('');
        $('#mdThongBaoBody #tb_tieu_de').val('');
        $('#dv_thong_bao_success').hide();
        $('#dv_thong_bao_error').hide();
    }
    
    function postFormThongBao(){   
        $('#dv_thong_bao_success').hide();
        $('#dv_thong_bao_error').hide();
        var em_id = $('#mdThongBaoBody #tb_cap_nhat_id').val();
        var tb_title = $('#mdThongBaoBody #tb_tieu_de').val();
        var tb_content = tinyMCE.get('tb_noi_dung').getContent();
        if(tb_title !='' && tb_content!=''){
            $("#btn_gui_thong_bao").attr("disabled", "disabled");
            $.post( site_url+'/canhan/thongbao/jqnewtb', {
                em_id: em_id, 
                tb_title: tb_title, 
                tb_content: tb_content
            }, function(data) {   
                $("#btn_gui_thong_bao").removeAttr("disabled");
                if(data.status){
                    $('#dv_thong_bao_success').show();
                    tinyMCE.get('tb_noi_dung').setContent('');
                    $('#mdThongBaoBody #tb_tieu_de').val('');
                }else{
                    $('#dv_thong_bao_error').show();
                }
            }, 'json');
        }else{
            alert('Bạn phải nhập đầy đủ tiêu đề và nội dung!');
        }         
    }
    
    function update_status(id_item, new_status){
        $.blockUI({
            message: '<h3>Đang thực hiện</h3>',
            css: {                         
                border: 'none', 
                padding: '15px', 
                backgroundColor: '#000', 
                '-webkit-border-radius': '10px', 
                '-moz-border-radius': '10px', 
                opacity: .5, 
                color: '#fff' 
            }
        }); 
        
        $.post( site_url+'/tochuccanbo/duyetchamcong/jqupdatestatus', {
            item_id: id_item, 
            item_status: new_status
        }, function(data) {    
            if(data.status){                
                $.success_ui('Thông báo!', 'Duyệt thành công!', 4000);
                $('span.cc_'+data.em_id).html(data.new_status);
                if(new_status>0){
                    $('#tr_id_'+data.em_id).addClass('success');
                }else{
                    $('#tr_id_'+data.em_id).removeClass('success');
                    $('span#icc_'+data.em_id).hide();
                }
            }else{
                $.error_ui('Thông báo', 'Không thể thực hiện được!', 4000); 
            }
        }, 'json');
            
    }
</script>