<?php
$list_phong_ban = array();
foreach ($this->list_phong_ban as $phong_ban) {
    $list_phong_ban[$phong_ban->pb_id] = $phong_ban->pb_name;
}

$list_phong_ban_options = array('0' => 'Tất cả');
foreach ($this->list_phong_ban_option as $phong_ban) {
    $list_phong_ban_options[$phong_ban->pb_id] = $phong_ban->pb_name;
}
?>
<h5>Duyệt chấm công</h5>               

<div class="main-content-box">  
    <form name="appForm" class="form-horizontal" method="post" action="">
        <div class="control-group">
            <label class="control-label">Phòng ban</label>
            <div class="controls">
                <?php
                echo $this->formSelect('sl_phong_ban', $this->pb_id, array('onchange' => 'on_choose_phong_ban()'), $list_phong_ban_options);
                ?>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Tháng</label>
            <div class="controls">
                <div class="input-append">
                    <input class="span2" value="<?php echo $this->thang . '/' . $this->nam; ?>" id="txt_thang_nam" type="text" readonly="true"/>
                    <button class="btn" type="button" id="btn_chon_thang">Chọn tháng!</button>
                </div>
            </div>
        </div>
        <div class="clearfix">
        </div>
        <div class="btn-toolbar float_left">
            <div class="btn-group">
                <button class="btn" onclick="OnSubmitForm('<?php echo $this->baseUrl('tochuccanbo/duyetchamcong/updatestatus/status/1/thang/' . $this->thang . '/nam/' . $this->nam . '/phongban/' . $this->pb_id); ?>')"><i class="icon-ok-sign"></i> Duyệt</button>
                <button class="btn" onclick="OnSubmitForm('<?php echo $this->baseUrl('tochuccanbo/duyetchamcong/updatestatus/status/0/thang/' . $this->thang . '/nam/' . $this->nam . '/phongban/' . $this->pb_id); ?>')"><i class="icon-remove-sign"></i> Không duyệt</button>
            </div>
        </div>

        <div class="clearfix">
        </div>

        <table class="table table-bordered table-hover">
            <thead>
                <tr>  
                    <th class="checkall_style"><input type="checkbox" name="check_all" id="checkbox" onclick="checkedAll()"></th>
                    <th>Họ tên</th>
                    <th style="width: 120px;">Phòng ban</th>                    
                    <th style="width: 120px;">Đơn vị</th>
                    <th style="width: 140px;">Phòng tổ chức</th>
                    <th style="width: 90px;">Chức năng</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->list_nhan_vien as $item) {
                    $cham_cong = $this->viewGetChamCong($this->thang, $this->nam, $item->em_id);
                    $dv_status = $phong_to_chuc_status = 'Chưa duyệt';
                    $class = '';
                    if ($cham_cong) {
                        if ($cham_cong->c_don_vi_status == 0) {
                            $dv_status = 'Không duyệt';
                        }

                        if ($cham_cong->c_don_vi_status > 0) {
                            $dv_status = 'Đã duyệt';
                        }

                        if ($cham_cong->c_ptccb_status == 0) {
                            $phong_to_chuc_status = 'Không duyệt';
                            $class = 'error';
                        }

                        if ($cham_cong->c_ptccb_status > 0) {
                            $phong_to_chuc_status = 'Đã duyệt';
                            $class = 'success';
                        }
                    }
                    ?>  
                    <tr class="<?php echo $class; ?>" id="tr_id_<?php echo $item->em_id; ?>">
                        <td class="checkall_style"><input type="checkbox" name="cid[]" id="cid" value="<?php echo $item->em_id; ?>"></td>
                        <td><?php echo $item->em_ho . ' ' . $item->em_ten; ?></td>
                        <td style="width: 200px;"><?php echo $list_phong_ban[$item->em_phong_ban]; ?></td>
                        <td style="width: 100px;"><span class="cc_<?php echo $item->em_id; ?>"><?php echo $dv_status; ?></span></td>
                        <td style="width: 100px;">
                            <span class="cc_<?php echo $item->em_id; ?>"><?php echo $phong_to_chuc_status; ?></span>
                            <?php
                            if($cham_cong && $cham_cong->c_don_vi_status>0):
                            ?>
                            <i class="icon-ok-sign" onclick="update_status(<?php echo $cham_cong->c_id; ?>,1)"></i> <i class="icon-remove-sign" onclick="update_status(<?php echo $cham_cong->c_id; ?>,0)"></i>
                            <?php endif;?>
                        </td>
                        <td style="width: 130px;">
                            <div class="dropdown float_left" style="padding-right: 6px;">
                                <a class="btn btn-mini" id="drop_<?php echo $item->em_id; ?>" role="button" data-toggle="dropdown" href="#"><i class="icon-th-list"></i> Chức năng <b class="caret"></b></a>                                    
                                <ul id="menu1" class="dropdown-menu" role="menu" aria-labelledby="drop_<?php echo $item->em_id; ?>">
                                    <li role="presentation">
                                        <a role="menuitem" tabindex="-1" data-toggle="modal" href="#mdThongBao" title="Gửi thông báo" onclick="loadFormThongBao(<?php echo $item->em_id; ?>, '<?php echo $item->em_ho . ' ' . $item->em_ten; ?>')"><i class="icon-envelope"></i> Gửi thông báo</a>
                                    </li>                                
                                    <li role="presentation">
                                        <a role="menuitem" tabindex="-1" data-toggle="modal" href="#mdDetail" title="Chi tiết" onclick="loadFormChiTiet(<?php echo $item->em_id; ?>, <?php echo $this->thang; ?>, <?php echo $this->nam; ?>, '<?php echo $item->em_ho . ' ' . $item->em_ten; ?>')"><i class="icon-calendar"></i> Chi tiết</a>
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>

    </form>
</div>

<!-- Modal -->
<div id="mdThongBao" class="modal_xlager hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Thông Báo</h3>
    </div>
    <div class="modal-body" id="mdThongBaoBody">
        <div class="alert alert-error" id="dv_thong_bao_error" style="display: none;">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h5>Thông báo!</h5>
            Cập nhật không thành công!
        </div>

        <div class="alert alert-success" id="dv_thong_bao_success" style="display: none;">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h5>Thông báo!</h5>
            Cập nhật thành công!
        </div>

        <form class="form-horizontal">
            <input type="hidden" id="tb_cap_nhat_id" value=""/>

            <div class="control-group">
                <label class="control-label" for="tb_can_bo">Người nhận</label>
                <div class="controls" id="tb_can_bo">

                </div>            
            </div>
            <div class="control-group">
                <label class="control-label" for="tb_tieu_de">Tiêu đề</label>
                <div class="controls">
                    <?php echo $this->formText('tb_tieu_de', null, array('class' => 'input-xxlarge', 'placeholder' => '')); ?>                   
                </div>            
            </div>
            <div class="control-group">
                <label class="control-label" for="tb_noi_dung">Nội dung</label>
                <div class="controls">
                    <?php echo $this->formTextarea('tb_noi_dung', null, array('class' => 'input-xlarge', 'rows' => 5)); ?>                   
                </div>            
            </div>
        </form>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Đóng</button>
        <button class="btn btn-primary" onclick="postFormThongBao();" id="btn_gui_thong_bao">Gửi thông báo</button>
    </div>
</div>

<div id="mdDetail" class="modal_xxlager hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myDetailLabel">Chi tiết</h3>
    </div>
    <div class="modal-body" id="mdDetailBody">
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Đóng</button>        
    </div>
</div>

<script>
    var currentYear = <?php echo $this->nam; ?>;    
    var options = {
        pattern: 'mm/yyyy', // Default is 'mm/yyyy' and separator char is not mandatory 
        startYear: 2013,
        selectedYear: currentYear,
        monthNames: ['Tháng 1', 'Tháng 2', 'Tháng 3', 'Tháng 4', 'Tháng 5', 'Tháng 6', 'Tháng 7', 'Tháng 8', 'Tháng 9', 'Tháng 10', 'Tháng 11', 'Tháng 12']
    };

    var phong_ban = $('#sl_phong_ban').val();
    $('#txt_thang_nam').monthpicker(options);

    $('#txt_thang_nam').monthpicker().bind('monthpicker-click-month', function (e, month, year) { 
        window.location = site_url+'/tochuccanbo/duyetchamcong/index/thang/'+month+'/nam/'+year+'/phongban/'+phong_ban;
    });

    $('#btn_chon_thang').bind('click', function () {
        $('#txt_thang_nam').monthpicker('show');
    });
    
    function on_choose_phong_ban(){
        var phong_ban = $('#sl_phong_ban').val();
        var c_date = $('#txt_thang_nam').val();
        var date_array = c_date.split("/");
        var d = new Date(),
        c_m = d.getMonth(),
        c_y = d.getFullYear();
        if(date_array.length==2 && $.isNumeric(date_array[0]) && $.isNumeric(date_array[1])){
            c_m = date_array[0];
            c_y = date_array[1];
        }        
        window.location = site_url+'/tochuccanbo/duyetchamcong/index/thang/'+c_m+'/nam/'+c_y+'/phongban/'+phong_ban;
    }
    function loadFormChiTiet(em_id, thang, nam, em_name){
        $('#myDetailLabel').html(em_name);       
        $('#mdDetailBody').html('Đang tải dữ liệu');
        $('#mdDetailBody').load(site_url+'/tochuccanbo/duyetchamcong/detail/thang/'+thang+'/nam/'+nam+'/em/'+em_id+' #dv_cham_cong_chi_tiet', function(){
         
        });
    }
    
    function loadFormThongBao(em_id, em_name){        
        $('#mdThongBaoBody #tb_cap_nhat_id').val(em_id);
        $('#mdThongBaoBody #tb_can_bo').html('<strong>'+em_name+'</strong>');
        tinyMCE.get('tb_noi_dung').setContent('');
        $('#mdThongBaoBody #tb_tieu_de').val('');
        $('#dv_thong_bao_success').hide();
        $('#dv_thong_bao_error').hide();
    }
    
    function postFormThongBao(){   
        $('#dv_thong_bao_success').hide();
        $('#dv_thong_bao_error').hide();
        var em_id = $('#mdThongBaoBody #tb_cap_nhat_id').val();
        var tb_title = $('#mdThongBaoBody #tb_tieu_de').val();
        var tb_content = tinyMCE.get('tb_noi_dung').getContent();
        if(tb_title !='' && tb_content!=''){
            $("#btn_gui_thong_bao").attr("disabled", "disabled");
            $.post( site_url+'/canhan/thongbao/jqnewtb', {
                em_id: em_id, 
                tb_title: tb_title, 
                tb_content: tb_content
            }, function(data) {   
                $("#btn_gui_thong_bao").removeAttr("disabled");
                if(data.status){
                    $('#dv_thong_bao_success').show();
                    tinyMCE.get('tb_noi_dung').setContent('');
                    $('#mdThongBaoBody #tb_tieu_de').val('');
                }else{
                    $('#dv_thong_bao_error').show();
                }
            }, 'json');
        }else{
            alert('Bạn phải nhập đầy đủ tiêu đề và nội dung!');
        }         
    }
    
    function update_status(id_item, new_status){
        $.blockUI({
            message: '<h3>Đang thực hiện</h3>',
            css: {                         
                border: 'none', 
                padding: '15px', 
                backgroundColor: '#000', 
                '-webkit-border-radius': '10px', 
                '-moz-border-radius': '10px', 
                opacity: .5, 
                color: '#fff' 
            }
        }); 
        
        $.post( site_url+'/tochuccanbo/duyetchamcong/jqupdatestatus', {
            item_id: id_item, 
            item_status: new_status
        }, function(data) {    
            if(data.status){                
                $.success_ui('Thông báo!', 'Duyệt thành công!', 4000);
                $('span.cc_'+data.em_id).html(data.new_status);
                if(new_status>0){
                    $('#tr_id_'+data.em_id).addClass('success');
                }else{
                    $('#tr_id_'+data.em_id).removeClass('success');
                }
            }else{
                $.error_ui('Thông báo', 'Không thể thực hiện được!', 4000); 
            }
        }, 'json');
            
    }
</script>