
<h5>Thêm cán bộ mới</h5>               

<div class="main-content-box"> 
    <?php if ($this->error_message) : ?>
        <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h5>Thông báo!</h5>
            Thêm tài khoản mới không thành công vì:
            <ol>
                <?php foreach ($this->error_message as $message): ?>
                    <li><?php echo $message; ?></li>
                <?php endforeach; ?>
            </ol>
        </div> 
    <?php endif; ?>  
    <?php if ($this->success_message) : ?>
        <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h5>Thông báo!</h5>
            <?php echo $this->success_message; ?>
        </div>
    <?php endif; ?>  
    <form class="form-horizontal" method="post" action="">
        <fieldset>
            <legend>Thông tin cá nhân</legend>
            <div class="control-group">
                <label class="control-label" for="ho">Họ Tên</label>
                <div class="controls">
                    <?php echo $this->formText('ho', NULL, array('required' => '', 'class' => 'input-small', 'placeholder' => 'Họ')); ?>                    
                    <?php echo $this->formText('ten_dem', NULL, array('class' => 'input-small', 'placeholder' => 'Tên đệm')); ?>                    
                    <?php echo $this->formText('ten', NULL, array('required' => '', 'class' => 'input-small', 'placeholder' => 'Tên')); ?>  
                    <span class="help-inline">(*)</span>
                    <span class="help-block">Nhập đầy đủ Họ và Tên của cán bộ, Tên đệm có thể bỏ trống nếu không có.</span>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="ten_khac">Tên thường gọi</label>
                <div class="controls">
                    <?php echo $this->formText('ten_khac', NULL, array('class' => 'input-medium', 'placeholder' => 'Tên thường gọi')); ?> 
                    <span class="help-block">Tên gọi khác nếu có.</span>
                </div>
            </div>            
            <div class="control-group">
                <label class="control-label" for="anh_the">Ảnh thẻ</label>
                <div class="controls">
                    <img src="<?php echo $this->baseUrl('anh_the.jpg'); ?>" class="img-polaroid anh_the">
                    <?php echo $this->formFile('anh_the'); ?>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="gioi_tinh">Giới tính</label>
                <div class="controls">
                    <?php
                    $gioi_tinh_options = array();
                    $gioi_tinh_options[0] = 'Nữ';
                    $gioi_tinh_options[1] = 'Nam';

                    echo $this->formSelect('gioi_tinh', null, null, $gioi_tinh_options);
                    ?>                    
                </div>
            </div> 
            <div class="control-group">
                <label class="control-label" for="ngay_sinh">Ngày sinh</label>
                <div class="controls">
                    <?php
                    $ngay_options = array();
                    for ($i = 1; $i <= 31; $i++) {
                        $ngay_options[$i] = $i;
                    }

                    $thang_options = array();
                    for ($i = 1; $i <= 12; $i++) {
                        $thang_options[$i] = $i;
                    }
                    $nam_options = array();
                    for ($i = 1900; $i <= date('Y'); $i++) {
                        $nam_options[$i] = $i;
                    }
                    echo $this->formSelect('ngay_sinh', null, array('class' => 'input-small'), $ngay_options);
                    echo '<span class="help-inline"> / </span>';
                    echo $this->formSelect('thang_sinh', null, array('class' => 'input-small'), $thang_options);
                    echo '<span class="help-inline"> / </span>';
                    echo $this->formSelect('nam_sinh', null, array('class' => 'input-small'), $nam_options);
                    ?>                    
                </div>
            </div> 

            <div class="control-group">
                <label class="control-label" for="home_phone">Điện thoại</label>
                <div class="controls">
                    <?php echo $this->formText('home_phone', NULL, array('class' => 'input-small', 'placeholder' => 'Điện thoại')); ?>                    
                    <?php echo $this->formText('phone', NULL, array('placeholder' => 'Di động')); ?>                    
                </div>
            </div> 
            <div class="control-group">
                <label class="control-label" for="noi_sinh">Nơi sinh</label>
                <div class="controls">
                    <?php echo $this->formText('noi_sinh', NULL, array('class' => 'input-xlarge')); ?>                    

                </div>
            </div> 
            <div class="control-group">
                <label class="control-label" for="que_quan">Quê quán</label>
                <div class="controls">
                    <?php echo $this->formText('que_quan', NULL, array('class' => 'input-xlarge')); ?>                    

                </div>
            </div> 
            <div class="control-group">
                <label class="control-label" for="dia_chi">Địa chỉ</label>
                <div class="controls">
                    <?php echo $this->formText('dia_chi', NULL, array('class' => 'input-xlarge')); ?> 
                </div>
            </div> 


            <div class="control-group">
                <label class="control-label" for="dia_chi_tinh">Tỉnh</label>
                <div class="controls">
                    <?php
                    $tinh_options = array(0 => '');
                    foreach ($this->list_tinh as $tinh) {
                        $tinh_options[$tinh->tinh_id] = $tinh->tinh_name;
                    }
                    echo $this->formSelect('dia_chi_tinh', null, array('class' => 'input-medium'), $tinh_options);
                    ?>                    

                </div>
            </div> 

            <div class="control-group">
                <label class="control-label" for="dia_chi_huyen">Huyện</label>
                <div class="controls">
                    <?php
                    $huyen_options = array(0 => '');
                    foreach ($this->list_huyen as $huyen) {
                        $huyen_options[$huyen->huyen_id] = $huyen->huyen_name;
                    }
                    echo $this->formSelect('dia_chi_huyen', null, array('class' => 'input-medium'), $huyen_options);
                    ?> 
                </div>
            </div> 

            <div class="control-group">
                <label class="control-label" for="dan_toc">Dân tộc</label>
                <div class="controls">
                    <?php
                    $dan_toc_options = array(0 => '');
                    foreach ($this->list_dan_toc as $dan_toc) {
                        $dan_toc_options[$dan_toc->dt_id] = $dan_toc->dt_name;
                    }
                    echo $this->formSelect('dan_toc', null, array('class' => 'input-medium'), $dan_toc_options);
                    ?> 
                </div>
            </div> 


        </fieldset>

        <fieldset>
            <legend>
                Thông tin viên chức
            </legend>
            <div class="control-group">
                <label class="control-label" for="so_cong_chuc">Số công chức</label>
                <div class="controls">
                    <?php echo $this->formText('so_cong_chuc', NULL, array('class' => 'input-medium', 'placeholder' => 'Số công chức')); ?> 
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="chuc_vu">Chức vụ</label>
                <div class="controls">
                    <?php
                    $chuc_vu_options = array(0 => '');
                    foreach ($this->list_chuc_vu as $chuc_vu) {
                        $chuc_vu_options[$chuc_vu->cv_id] = $chuc_vu->cv_name;
                    }
                    echo $this->formSelect('chuc_vu', null, array('class' => 'input-medium'), $chuc_vu_options);
                    ?> 
                </div>
            </div> 

            <div class="control-group">
                <label class="control-label" for="phong_ban">Đơn vị</label>
                <div class="controls">
                    <?php
                    $phong_ban_options = array(0 => '');
                    foreach ($this->list_phong_ban as $phong_ban) {
                        $phong_ban_options[$phong_ban->pb_id] = $phong_ban->pb_name;
                    }
                    echo $this->formSelect('phong_ban', null, array('class' => 'input-medium'), $phong_ban_options);
                    ?> 
                </div>
            </div>              

            <div class="control-group">
                <label class="control-label" for="phong_ban">Ngày tuyển dụng</label>
                <div class="controls">
                    <?php
                    echo $this->formSelect('ngay_tuyen_dung', null, array('class' => 'input-small'), $ngay_options);
                    echo '<span class="help-inline"> / </span>';
                    echo $this->formSelect('thang_tuyen_dung', null, array('class' => 'input-small'), $thang_options);
                    echo '<span class="help-inline"> / </span>';
                    echo $this->formSelect('nam_tuyen_dung', null, array('class' => 'input-small'), $nam_options);
                    ?> 
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="ngach_cong_chuc">Ngạch công chức</label>
                <div class="controls">
                    <?php
                    $ngach_cong_chuc_options = array(0 => '');
                    foreach ($this->list_ngach_cong_chuc as $ngach_cong_chuc) {
                        $ngach_cong_chuc_options[$ngach_cong_chuc->ncc_id] = $ngach_cong_chuc->ncc_name;
                    }
                    echo $this->formSelect('ngach_cong_chuc', null, array('class' => 'input-medium'), $ngach_cong_chuc_options);
                    ?> 
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="cong_viec">Công việc</label>
                <div class="controls">

                    <?php echo $this->formText('cong_viec', NULL, array('class' => 'input-xlarge')); ?> 
                </div>
            </div>
            
            <div class="control-group">
                <label class="control-label" for="chuyen_mon">Chuyên môn</label>
                <div class="controls">

                    <?php echo $this->formText('chuyen_mon', NULL, array('class' => 'input-xlarge')); ?> 
                </div>
            </div>

        </fieldset>
        <fieldset>
            <legend>Thông tin Đảng - Đoàn</legend>
            <div class="control-group">
                <label class="control-label" for="chuc_vu_dang">Chức vụ đảng</label>
                <div class="controls">
                    <?php
                    $dang_options = array(0 => '', 1 => 'Bí thư', 2 => 'Phó bí thư', 3 => 'Ủy viên', 4 => 'Đảng viên');
                    echo $this->formSelect('chuc_vu_dang', null, null, $dang_options);
                    ?>                     
                </div>
            </div> 
            <div class="control-group">
                <label class="control-label" for="ngay_dang">Ngày vào đảng</label>
                <div class="controls">
                    <?php
                    echo $this->formSelect('ngay_dang', null, array('class' => 'input-small'), $ngay_options);
                    echo '<span class="help-inline"> / </span>';
                    echo $this->formSelect('thang_dang', null, array('class' => 'input-small'), $thang_options);
                    echo '<span class="help-inline"> / </span>';
                    echo $this->formSelect('nam_dang', null, array('class' => 'input-small'), $nam_options);
                    ?>                     
                </div>
            </div> 

            <div class="control-group">
                <label class="control-label" for="chuc_vu_doan">Chức vụ đoàn</label>
                <div class="controls">
                    <?php
                    $dang_options = array(0 => '', 1 => 'Bí thư', 2 => 'Phó bí thư', 3 => 'Ủy viên', 4 => 'Đảng viên');
                    echo $this->formSelect('chuc_vu_doan', null, null, $dang_options);
                    ?>                     
                </div>
            </div> 
            <div class="control-group">
                <label class="control-label" for="ngay_doan">Ngày vào đoàn</label>
                <div class="controls">
                    <?php
                    echo $this->formSelect('ngay_doan', null, array('class' => 'input-small'), $ngay_options);
                    echo '<span class="help-inline"> / </span>';
                    echo $this->formSelect('thang_doan', null, array('class' => 'input-small'), $thang_options);
                    echo '<span class="help-inline"> / </span>';
                    echo $this->formSelect('nam_doan', null, array('class' => 'input-small'), $nam_options);
                    ?>                     
                </div>
            </div> 
            <div class="control-group">
                <label class="control-label" for="chuc_vu_cong_doan">Chức vụ công đoàn</label>
                <div class="controls">
                    <?php
                    $cong_doan_options = array(0 => '', 1 => 'Chủ tịch', 2 => 'Phó chủ tịch', 3 => 'Ủy viên', 4 => 'Công đoàn viên');
                    echo $this->formSelect('chuc_vu_cong_doan', null, null, $cong_doan_options);
                    ?>                     
                </div>
            </div>
        </fieldset>
        
        <fieldset>
            <legend>Thông tin học vấn</legend>
            <div class="control-group">
                <label class="control-label" for="van_hoa_pt">Văn hóa phổ thông</label>
                <div class="controls">

                    <?php echo $this->formText('van_hoa_pt', NULL, array('class' => 'input-xlarge')); ?> 
                </div>
            </div>
            
            <div class="control-group">
                <label class="control-label" for="hoc_ham">Học hàm cao nhất</label>
                <div class="controls">
                    <?php
                    $hoc_ham_options = array(0 => '');
                    foreach ($this->list_hoc_ham as $hoc_ham) {
                        $hoc_ham_options[$hoc_ham->hh_id] = $hoc_ham->hh_name;
                    }
                    echo $this->formSelect('hoc_ham', null, array('class' => 'input-medium'), $hoc_ham_options);
                    ?> 
                </div>
            </div>
            
            <div class="control-group">
                <label class="control-label" for="bang_cap">Bằng cấp cao nhất</label>
                <div class="controls">
                    <?php
                    $bang_cap_options = array(0 => '');
                    foreach ($this->list_bang_cap as $bang_cap) {
                        $bang_cap_options[$bang_cap->bc_id] = $bang_cap->bc_name;
                    }
                    echo $this->formSelect('bang_cap', null, array('class' => 'input-medium'), $bang_cap_options);
                    ?> 
                </div>
            </div>
            
            <div class="control-group">
                <label class="control-label" for="bang_cap">Ngoại ngữ</label>
                <div class="controls">
                    <?php
                    $ngoai_ngu_options = array(0 => '');
                    $tin_hoc_options = array(0 => '');
                    $loai_khac_options = array(0 => '');
                    foreach ($this->list_chung_chi as $chung_chi) {
                        switch ($chung_chi->cc_type) {
                            case 1:
                                $ngoai_ngu_options[$chung_chi->cc_id] = $chung_chi->cc_name;
                                break;
                            case 2:
                                $tin_hoc_options[$chung_chi->cc_id] = $chung_chi->cc_name;
                                break;

                            default:
                                $loai_khac_options[$chung_chi->cc_id] = $chung_chi->cc_name;
                                break;
                        }                        
                    }
                    echo $this->formSelect('bang_cap', null, array('class' => 'input-medium'), $ngoai_ngu_options);
                    ?> 
                </div>
            </div>
            
            <div class="control-group">
                <label class="control-label" for="tin_hoc">Tin học</label>
                <div class="controls">
                    <?php                    
                    echo $this->formSelect('tin_hoc', null, array('class' => 'input-medium'), $tin_hoc_options);
                    ?> 
                </div>
            </div>
            
            <div class="control-group">
                <label class="control-label" for="chung_chi_khac">Chứng chỉ khác</label>
                <div class="controls">
                    <?php
                    
                    echo $this->formSelect('chung_chi_khac', null, array('class' => 'input-medium'), $loai_khac_options);
                    ?> 
                </div>
            </div>
            
        </fieldset>

        <div class="control-group">
            <label class="control-label" for="status">Trạng thái</label>
            <div class="controls">
                <?php
                $status_options = array(1 => 'Sử dụng', 0 => 'Khóa');
                echo $this->formSelect('status', null, null, $status_options);
                ?>                     
            </div>
        </div> 

        <div class="control-group">
            <div class="controls">
                <p>
                    <button class="btn btn-small btn-primary" type="submit">Thêm mới</button>
                    <a class="btn btn-small" type="button" href="<?php echo $this->baseUrl('tochuccanbo/employees/index/page/' . $this->arrParam['page']); ?>">Quay lại</a>
                </p>
            </div>
        </div>
    </form>
</div> 