<h5>Thêm cán bộ mới</h5>               

<div class="main-content-box"> 
    <?php if ($this->error_message) : ?>
        <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h5>Thông báo!</h5>
            Thêm mới không thành công vì:
            <ol>
                <?php foreach ($this->error_message as $message): ?>
                    <li><?php echo $message; ?></li>
                <?php endforeach; ?>
            </ol>
        </div> 
    <?php endif; ?>  
    <?php if ($this->success_message) : ?>
        <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h5>Thông báo!</h5>
            <?php echo $this->success_message; ?>
        </div>
    <?php endif; ?>  
    <form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
        <fieldset>
            <legend>Thông tin cá nhân</legend>
            <div class="control-group">
                <label class="control-label" for="em_ho">Họ Tên</label>
                <div class="controls">
                    <?php echo $this->formText('em_ho', $this->arrParam['em_ho'], array('required' => '', 'class' => 'input-small', 'placeholder' => 'Họ')); ?>                    
                    <?php echo $this->formText('em_ten_dem', $this->arrParam['em_ten_dem'], array('class' => 'input-small', 'placeholder' => 'Tên đệm')); ?>                    
                    <?php echo $this->formText('em_ten', $this->arrParam['em_ten'], array('required' => '', 'class' => 'input-small', 'placeholder' => 'Tên')); ?>  
                    <span class="help-inline">(*)</span>
                    <span class="help-block">Nhập đầy đủ Họ và Tên của cán bộ, Tên đệm có thể bỏ trống nếu không có.</span>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="em_ten_khac">Tên thường gọi</label>
                <div class="controls">
                    <?php echo $this->formText('em_ten_khac', $this->arrParam['em_ten_khac'], array('class' => 'input-medium', 'placeholder' => 'Tên thường gọi')); ?> 
                    <span class="help-block">Tên gọi khác nếu có.</span>
                </div>
            </div>    

            <div class="control-group">
                <label class="control-label" for="em_so_chung_minh_thu">Số chứng minh thư</label>
                <div class="controls">
                    <?php echo $this->formText('em_so_chung_minh_thu', $this->arrParam['em_so_chung_minh_thu'], array('class' => 'input-medium', 'placeholder' => 'Số chứng minh thư')); ?> 
                </div>
            </div>            
            <div class="control-group">
                <label class="control-label" for="em_anh_the">Ảnh thẻ</label>
                <div class="controls">
                    <img src="<?php echo $this->baseUrl('anh_the.jpg'); ?>" class="img-polaroid anh_the">
                    <?php echo $this->formFile('em_anh_the'); ?>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="em_gioi_tinh">Giới tính</label>
                <div class="controls">
                    <?php
                    $gioi_tinh_options = array();
                    $gioi_tinh_options[0] = 'Nữ';
                    $gioi_tinh_options[1] = 'Nam';

                    echo $this->formSelect('em_gioi_tinh', $this->arrParam['em_gioi_tinh'], null, $gioi_tinh_options);
                    ?>                    
                </div>
            </div> 
            <div class="control-group">
                <label class="control-label" for="ngay_sinh">Ngày sinh</label>
                <div class="controls">
                    <?php echo $this->formText('ngay_sinh', $this->arrParam['ngay_sinh'], array('class' => 'input-medium', 'placeholder' => 'Ngày sinh', 'readonly' => 'readonly')); ?>                    
                </div>
            </div> 

            <div class="control-group">
                <label class="control-label" for="em_home_phone">Điện thoại</label>
                <div class="controls">
                    <?php echo $this->formText('em_home_phone', $this->arrParam['em_home_phone'], array('class' => 'input-small', 'placeholder' => 'Điện thoại')); ?>                    
                    <?php echo $this->formText('em_phone', $this->arrParam['em_phone'], array('placeholder' => 'Di động')); ?>                    
                </div>
            </div> 
            <div class="control-group">
                <label class="control-label" for="em_noi_sinh">Nơi sinh</label>
                <div class="controls">
                    <?php echo $this->formText('em_noi_sinh', $this->arrParam['em_noi_sinh'], array('class' => 'input-xlarge')); ?>                    

                </div>
            </div> 
            <div class="control-group">
                <label class="control-label" for="em_que_quan">Quê quán</label>
                <div class="controls">
                    <?php echo $this->formText('em_que_quan', $this->arrParam['em_que_quan'], array('class' => 'input-xlarge')); ?>                    

                </div>
            </div> 
            <div class="control-group">
                <label class="control-label" for="em_dia_chi">Địa chỉ</label>
                <div class="controls">
                    <?php echo $this->formText('em_dia_chi', $this->arrParam['em_dia_chi'], array('class' => 'input-xlarge')); ?> 
                </div>
            </div> 


            <div class="control-group">
                <label class="control-label" for="em_dia_chi_tinh">Tỉnh</label>
                <div class="controls">
                    <?php
                    $tinh_options = array(0 => '');
                    foreach ($this->list_tinh as $tinh) {
                        $tinh_options[$tinh->tinh_id] = $tinh->tinh_name;
                    }
                    echo $this->formSelect('em_dia_chi_tinh', null, array('class' => 'input-medium', 'onchange' => 'changeTinh()'), $tinh_options);
                    ?>                    

                </div>
            </div> 

            <div class="control-group">
                <label class="control-label" for="em_dia_chi_huyen">Huyện</label>
                <div class="controls">
                    <?php
                    $huyen_options = array(0 => '');
                    foreach ($this->list_huyen as $huyen) {
                        $huyen_options[$huyen->huyen_id] = $huyen->huyen_name;
                    }
                    echo $this->formSelect('em_dia_chi_huyen', null, array('class' => 'input-medium'), $huyen_options);
                    ?> 
                </div>
            </div> 

            <div class="control-group">
                <label class="control-label" for="em_dan_toc">Dân tộc</label>
                <div class="controls">
                    <?php
                    $dan_toc_options = array(0 => '');
                    foreach ($this->list_dan_toc as $dan_toc) {
                        $dan_toc_options[$dan_toc->dt_id] = $dan_toc->dt_name;
                    }
                    echo $this->formSelect('em_dan_toc', $this->arrParam['em_dan_toc'], array('class' => 'input-medium'), $dan_toc_options);
                    ?> 
                </div>
            </div> 


        </fieldset>

        <fieldset>
            <legend>
                Thông tin viên chức
            </legend>
            <div class="control-group">
                <label class="control-label" for="em_so_cong_chuc">Số công chức</label>
                <div class="controls">
                    <?php echo $this->formText('em_so_cong_chuc', $this->arrParam['em_so_cong_chuc'], array('class' => 'input-medium', 'placeholder' => 'Số công chức')); ?> 
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="em_chuc_vu">Chức vụ</label>
                <div class="controls">
                    <?php
                    $chuc_vu_options = array(0 => '');
                    foreach ($this->list_chuc_vu as $chuc_vu) {
                        $chuc_vu_options[$chuc_vu->cv_id] = $chuc_vu->cv_name;
                    }
                    echo $this->formSelect('em_chuc_vu', $this->arrParam['em_chuc_vu'], array('class' => 'input-medium'), $chuc_vu_options);
                    ?> 
                </div>
            </div> 

            <div class="control-group">
                <label class="control-label" for="em_phong_ban">Đơn vị</label>
                <div class="controls">
                    <?php
                    $phong_ban_options = array(0 => '');
                    foreach ($this->list_phong_ban as $phong_ban) {
                        $phong_ban_options[$phong_ban->pb_id] = $phong_ban->pb_name;
                    }
                    echo $this->formSelect('em_phong_ban', $this->arrParam['em_phong_ban'], array('class' => 'input-medium'), $phong_ban_options);
                    ?> 
                </div>
            </div>              

            <div class="control-group">
                <label class="control-label" for="ngay_tuyen_dung">Ngày tuyển dụng</label>
                <div class="controls">
                    <?php echo $this->formText('ngay_tuyen_dung', $this->arrParam['ngay_tuyen_dung'], array('class' => 'input-medium', 'placeholder' => 'Ngày tuyển dụng', 'readonly' => 'readonly')); ?> 

                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="em_ngach_cong_chuc">Ngạch công chức</label>
                <div class="controls">
                    <?php
                    $ngach_cong_chuc_options = array(0 => '');
                    foreach ($this->list_ngach_cong_chuc as $ngach_cong_chuc) {
                        $ngach_cong_chuc_options[$ngach_cong_chuc->ncc_id] = $ngach_cong_chuc->ncc_name;
                    }
                    echo $this->formSelect('em_ngach_cong_chuc', $this->arrParam['em_ngach_cong_chuc'], array('class' => 'input-medium'), $ngach_cong_chuc_options);
                    ?> 
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="em_cong_viec">Công việc</label>
                <div class="controls">

                    <?php echo $this->formText('em_cong_viec', $this->arrParam['em_cong_viec'], array('class' => 'input-xlarge')); ?> 
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="em_chuyen_mon">Chuyên môn</label>
                <div class="controls">

                    <?php echo $this->formText('em_chuyen_mon', $this->arrParam['em_chuyen_mon'], array('class' => 'input-xlarge')); ?> 
                </div>
            </div>

        </fieldset>
        <fieldset>
            <legend>Thông tin Đảng - Đoàn</legend>
            <div class="control-group">
                <label class="control-label" for="em_chuc_vu_dang">Chức vụ đảng</label>
                <div class="controls">
                    <?php
                    $dang_options = array(0 => '');
                    foreach ($this->list_chuc_vu_dang as $dang) {
                        $dang_options[$dang->cvdang_id] = $dang->cvdang_name;
                    }
                    echo $this->formSelect('em_chuc_vu_dang', $this->arrParam['em_chuc_vu_dang'], null, $dang_options);
                    ?>                     
                </div>
            </div> 
            <div class="control-group">
                <label class="control-label" for="ngay_dang">Ngày vào đảng</label>
                <div class="controls">                    
                    <?php echo $this->formText('ngay_dang', $this->arrParam['ngay_dang'], array('class' => 'input-medium', 'placeholder' => 'Ngày vào đảng', 'readonly' => 'readonly')); ?>                    
                </div>
            </div> 

            <div class="control-group">
                <label class="control-label" for="em_chuc_vu_doan">Chức vụ đoàn</label>
                <div class="controls">
                    <?php
                    $doan_options = array(0 => '');
                    foreach ($this->list_chuc_vu_doan as $doan) {
                        $doan_options[$doan->cvdoan_id] = $doan->cvdoan_name;
                    }
                    echo $this->formSelect('em_chuc_vu_doan', $this->arrParam['em_chuc_vu_doan'], null, $doan_options);
                    ?>                     
                </div>
            </div> 
            <div class="control-group">
                <label class="control-label" for="ngay_doan">Ngày vào đoàn</label>
                <div class="controls">
                    <?php echo $this->formText('ngay_doan', $this->arrParam['ngay_doan'], array('class' => 'input-medium', 'placeholder' => 'Ngày vào đoàn', 'readonly' => 'readonly')); ?>                    
                </div>
            </div> 
            <div class="control-group">
                <label class="control-label" for="em_chuc_vu_cong_doan">Chức vụ công đoàn</label>
                <div class="controls">
                    <?php
                    $cong_doan_options = array(0 => '');
                    foreach ($this->list_chuc_vu_cong_doan as $cdoan) {
                        $cong_doan_options[$cdoan->cvcdoan_id] = $cdoan->cvcdoan_name;
                    }
                    echo $this->formSelect('em_chuc_vu_cong_doan', $this->arrParam['em_chuc_vu_cong_doan'], null, $cong_doan_options);
                    ?>                     
                </div>
            </div>
        </fieldset>

        <fieldset>
            <legend>Thông tin học vấn</legend>
            <div class="control-group">
                <label class="control-label" for="em_van_hoa_pt">Văn hóa phổ thông</label>
                <div class="controls">

                    <?php echo $this->formText('em_van_hoa_pt', $this->arrParam['em_van_hoa_pt'], array('class' => 'input-xlarge')); ?> 
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="em_hoc_ham">Học hàm cao nhất</label>
                <div class="controls">
                    <?php
                    $hoc_ham_options = array(0 => '');
                    foreach ($this->list_hoc_ham as $hoc_ham) {
                        $hoc_ham_options[$hoc_ham->hh_id] = $hoc_ham->hh_name;
                    }
                    echo $this->formSelect('em_hoc_ham', $this->arrParam['em_hoc_ham'], array('class' => 'input-medium'), $hoc_ham_options);
                    ?> 
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="em_bang_cap">Bằng cấp cao nhất</label>
                <div class="controls">
                    <?php
                    $bang_cap_options = array(0 => '');
                    foreach ($this->list_bang_cap as $bang_cap) {
                        $bang_cap_options[$bang_cap->bc_id] = $bang_cap->bc_name;
                    }
                    echo $this->formSelect('em_bang_cap', $this->arrParam['em_bang_cap'], array('class' => 'input-medium'), $bang_cap_options);
                    ?> 
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="em_ngoai_ngu">Ngoại ngữ</label>
                <div class="controls">
                    <?php
                    $ngoai_ngu_options = array(0 => '');
                    $tin_hoc_options = array(0 => '');
                    $loai_khac_options = array(0 => '');
                    foreach ($this->list_chung_chi as $chung_chi) {
                        switch ($chung_chi->cc_type) {
                            case 1:
                                $ngoai_ngu_options[$chung_chi->cc_id] = $chung_chi->cc_name;
                                break;
                            case 2:
                                $tin_hoc_options[$chung_chi->cc_id] = $chung_chi->cc_name;
                                break;

                            default:
                                $loai_khac_options[$chung_chi->cc_id] = $chung_chi->cc_name;
                                break;
                        }
                    }
                    echo $this->formSelect('em_ngoai_ngu', $this->arrParam['em_ngoai_ngu'], array('class' => 'input-medium'), $ngoai_ngu_options);
                    ?> 
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="em_tin_hoc">Tin học</label>
                <div class="controls">
                    <?php
                    echo $this->formSelect('em_tin_hoc', $this->arrParam['em_tin_hoc'], array('class' => 'input-medium'), $tin_hoc_options);
                    ?> 
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="em_chung_chi_khac">Chứng chỉ khác</label>
                <div class="controls">
                    <?php
                    echo $this->formSelect('em_chung_chi_khac', $this->arrParam['em_chung_chi_khac'], array('class' => 'input-medium'), $loai_khac_options);
                    ?> 
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="em_bang_scan_upload">Ảnh/Scan bằng</label>
                <div class="controls">
                    <div id="queue"></div>
                    <input id="bang_scan_upload" name="em_bang_scan_upload" type="file" multiple="true"/>
                    <table class="table" id="tbl_anh_bang_cap">
                        <tbody id="tbd_anh_bang_cap">
                            <?php
                            foreach ($this->arrParam['anh_bang_cap'] as $anh_scan) {
                                $random_id = mt_rand();
                                echo '<tr id="' . $random_id . '"><td><input type="hidden" name="anh_bang_cap[]" value="' . $anh_scan . '"/><img src="' . $this->baseUrl('public/uploads/') . $anh_scan . '" class="img-polaroid anh_bang_cap"></td> <td> <button class="btn btn-small btn btn-danger" type="button" onclick="deleteAnhScan(\'' . $random_id . '\')">Xóa</button></td></tr>';
                            }
                            ?>
                        </tbody>
                    </table>                    
                </div>
            </div>

        </fieldset>

        <fieldset>
            <legend>Trạng thái</legend>
            <div class="control-group">
                <label class="control-label" for="em_status">Trạng thái</label>
                <div class="controls">
                    <?php
                    $status_options = array(1 => 'Sử dụng', 0 => 'Khóa');
                    echo $this->formSelect('em_status', $this->arrParam['em_status'], null, $status_options);
                    ?>                     
                </div>
            </div> 
        </fieldset>

        <div class="control-group">
            <div class="controls">
                <p>                    
                    <button class="btn btn-small btn-primary" type="submit">Thêm mới</button>
                    <a class="btn btn-small" type="button" href="<?php echo $this->baseUrl('tochuccanbo/employees/index/page/' . $this->arrParam['page']); ?>">Quay lại</a>
                </p>
            </div>
        </div>
    </form>
</div> 

<script type="text/javascript">
<?php $timestamp = time(); ?>
    $(function() {
        $('#bang_scan_upload').uploadify({
            'formData'     : {
                'timestamp' : '<?php echo $timestamp; ?>',
                'token'     : '<?php echo md5('unique_salt' . $timestamp); ?>'
            },
            'checkExisting' : '<?php echo $this->baseUrl('public/uploads/check-exists.php'); ?>',
            'swf'      : '<?php echo $this->baseUrl('public/js/uploadify/uploadify.swf'); ?>',
            'uploader' : '<?php echo $this->baseUrl('public/uploads/uploadify.php'); ?>',
            'fileTypeDesc' : 'Image Files',
            'fileTypeExts' : '*.gif; *.jpg; *.png; *.jpeg',
            'onUploadError' : function(file, errorCode, errorMsg, errorString) {
                alert('Tải ảnh/scan bằng cấp thất bại. Xin hãy thử lại.');
            },            
            'onUploadSuccess' : function(file, data, response) {
                data = $.parseJSON(data);
                if(!data.success){
                    alert('Upload không thành công.\n Xin hãy thử lại.');
                }else{   
                    var unix = Math.round(+new Date()/1000);
                    $('#tbd_anh_bang_cap').append("<tr id=\""+unix+"\"><td><input type=\"hidden\" name=\"anh_bang_cap[]\" value=\""+data.file_name+"\"/><img src=\"<?php echo $this->baseUrl('public/uploads/'); ?>" + data.file_name + "\" class=\"img-polaroid anh_bang_cap\"></td> <td> <button class=\"btn btn-small btn btn-danger\" type=\"button\" onclick=\"deleteAnhScan('"+unix+"')\">Xóa</button></td></tr>");
                }
            }
        });
        $( "#ngay_sinh" ).datepicker({
            changeMonth: true,
            changeYear: true,
            defaultDate: "+1w",
            numberOfMonths: 1,
            dateFormat: 'd/m/yy',
            showOn: "button",
            buttonImage: site_url+"/date-picker-icon.png",
            buttonImageOnly: true
        });
        $( "#ngay_dang" ).datepicker({
            changeMonth: true,
            changeYear: true,
            defaultDate: "+1w",
            numberOfMonths: 1,
            dateFormat: 'd/m/yy',
            showOn: "button",
            buttonImage: site_url+"/date-picker-icon.png",
            buttonImageOnly: true
        });
        $( "#ngay_doan" ).datepicker({
            changeMonth: true,
            changeYear: true,
            defaultDate: "+1w",
            numberOfMonths: 1,
            dateFormat: 'd/m/yy',
            showOn: "button",
            buttonImage: site_url+"/date-picker-icon.png",
            buttonImageOnly: true
        });
        $( "#ngay_tuyen_dung" ).datepicker({
            changeMonth: true,
            changeYear: true,
            defaultDate: "+1w",
            numberOfMonths: 1,
            dateFormat: 'd/m/yy',
            showOn: "button",
            buttonImage: site_url+"/date-picker-icon.png",
            buttonImageOnly: true
        });
    });    
    
    function changeTinh(){
        var tinh_id = $('#em_dia_chi_tinh').val();
        
        var select = $('#em_dia_chi_huyen');
        if(select.prop) {
            var options = select.prop('options');
        }
        else {
            var options = select.attr('options');
        }
        $('option', select).remove();


        $.getJSON( site_url+'/tochuccanbo/employees/gethuyen/tid/'+tinh_id, function( data ) {            
            $.each( data, function( key, val ) {
                select.append('<option value="'+val.id+'">'+val.name+'</option>');
            });
        });
    }
</script>