<?php
$thong_tin_info = array();
if($this->employee_info){
    $thong_tin_info['status'] = 1;
    $thong_tin_info['so_cong_chuc'] = $this->employee_info->em_so_cong_chuc;
    $thong_tin_info['chuc_vu'] = array('id' => $this->employee_info->em_chuc_vu, 'name' => $this->viewGetChucVuName($this->employee_info->em_chuc_vu));
    $thong_tin_info['phong_ban'] = array('id' => $this->employee_info->em_phong_ban, 'name' => $this->ViewGetPhongBanName($this->employee_info->em_phong_ban));
    $thong_tin_info['ngach_cong_chuc'] = array('id' => $this->employee_info->em_ngach_cong_chuc, 'name' => $this->ViewGetNgachCongChucName($this->employee_info->em_ngach_cong_chuc));;
    $thong_tin_info['cong_viec'] = $this->employee_info->em_cong_viec;
    $thong_tin_info['chuyen_mon'] = $this->employee_info->em_chuyen_mon;
}else{
    $thong_tin_info['status'] = 0;
}


echo json_encode($thong_tin_info);
?>