<?php
$thang_options = array();
for($i=1; $i<=12; $i++){
    $thang_options[$i] = $i;
}

$nam_options = array();
for($i=1900; $i<=2050; $i++){
    $nam_options[$i] = $i;
}
?>
<div id="dv_form_he_so">
    <?php if (sizeof($this->error_message)): ?>
        <div class="alert alert-error" id="dv_he_so_error">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h5>Thông báo!</h5>
            Cập nhật không thành công vì:
            <ol>
                <?php foreach ($this->error_message as $message): ?>
                    <li><?php echo $message; ?></li>
                <?php endforeach; ?>
            </ol>
        </div>
    <?php endif; ?>
    <?php if ($this->success_message): ?>
        <div class="alert alert-success" id="dv_he_so_success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h5>Thông báo!</h5>
            Cập nhật thành công!
        </div>
    <?php endif; ?>
    <form class="form-horizontal" action="" method="post" id="frm_update_heso">
        <input type="hidden" id="pc_cap_nhat_em_id" name="pc_cap_nhat_em_id" value="<?php echo $this->em_id; ?>"/>

        <div class="control-group">
            <label class="control-label" for="eh_loai_luong">Tính lương</label>
            <div class="controls">
                <?php
                $loai_luong_options = array(0 => 'Biên chế', 1 => 'Hợp đồng');
                if ($this->he_so)
                    echo $this->formSelect('eh_loai_luong', $this->he_so->eh_loai_luong, array('class' => 'input-large'), $loai_luong_options);
                else
                    echo $this->formSelect('eh_loai_luong', null, array('class' => 'input-large'), $loai_luong_options);
                ?> 
            </div>
        </div> 
        <div class="control-group">
            <label class="control-label" for="eh_giai_doan">Giai đoạn</label>
            <div class="controls">
                <?php
                $giai_doan_options = array(0 => 'Chính thức', 1 => 'Thử việc');
                if ($this->he_so)
                    echo $this->formSelect('eh_giai_doan', $this->he_so->eh_giai_doan, array('class' => 'input-large'), $giai_doan_options);
                else
                    echo $this->formSelect('eh_giai_doan', null, array('class' => 'input-large'), $giai_doan_options);
                ?> 
            </div>
        </div>
        
        <div class="control-group">
            <label class="control-label">Ngạch công chức</label>
            <div class="controls">
                <?php echo $this->viewGetNgachCongChucName($this->em_info->em_ngach_cong_chuc); ?>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="eh_bac_luong">Bậc lương</label>
            <div class="controls">                
                <div class="input-prepend input-append">    
                    <?php
                    $bac_luong_options = array(0 => '');
                    foreach ($this->bac_luong as $bl) {
                        $bac_luong_options[$bl->bl_id] = $bl->bl_name;
                    }

                    if ($this->he_so)
                        echo $this->formSelect('eh_bac_luong', $this->he_so->eh_bac_luong, array('onchange' => 'change_bac_luong(this, '.$this->em_info->em_ngach_cong_chuc.')'), $bac_luong_options);
                    else
                        echo $this->formSelect('eh_bac_luong', null, array('onchange' => 'change_bac_luong(this, '.$this->em_info->em_ngach_cong_chuc.')'), $bac_luong_options);
                    ?>                                    
                </div>    
            </div>            
        </div> 

        <div class="control-group">
            <label class="control-label" for="eh_he_so">Hệ số lương</label>
            <div class="controls">                
                <div class="input-prepend input-append">    
                    <?php
                    if ($this->he_so)
                        echo $this->formText('eh_he_so', $this->he_so->eh_he_so, array('class' => 'input-medium', 'placeholder' => ''));
                    else
                        echo $this->formText('eh_he_so', null, array('class' => 'input-medium', 'placeholder' => ''));
                    ?>                   
                    <span class="add-on">Hệ số</span>                    
                </div>    
            </div>            
        </div> 
        

        <div class="control-group">
            <label class="control-label" for="eh_thang_ap_dung">Áp dụng từ</label>
            <div class="controls">
                <?php
                if ($this->he_so) {
                    echo $this->formSelect('eh_thang_ap_dung', date('m', strtotime($this->he_so->eh_han_ap_dung)), array('class' => 'input-small'), $thang_options);
                    echo '<span class="help-inline"> / </span>';
                    echo $this->formSelect('eh_nam_ap_dung', date('Y', strtotime($this->he_so->eh_han_ap_dung)), array('class' => 'input-small'), $nam_options);
                } else {
                    echo $this->formSelect('eh_thang_ap_dung', null, array('class' => 'input-small'), $thang_options);
                    echo '<span class="help-inline"> / </span>';
                    echo $this->formSelect('eh_nam_ap_dung', null, array('class' => 'input-small'), $nam_options);
                }
                ?>    
                <span class="help-block">Thời điểm điều chỉnh hiện tại.</span>
            </div>
        </div>
        
        <div class="control-group">
            <label class="control-label" for="eh_thang_dieu_chinh">Ngày điều chỉnh</label>
            <div class="controls">
                <?php
                if ($this->he_so) {
                    echo $this->formSelect('eh_thang_dieu_chinh', date('m', strtotime($this->he_so->eh_han_dieu_chinh)), array('class' => 'input-small'), $thang_options);
                    echo '<span class="help-inline"> / </span>';
                    echo $this->formSelect('eh_nam_dieu_chinh', date('Y', strtotime($this->he_so->eh_han_dieu_chinh)), array('class' => 'input-small'), $nam_options);
                } else {
                    echo $this->formSelect('eh_thang_dieu_chinh', null, array('class' => 'input-small'), $thang_options);
                    echo '<span class="help-inline"> / </span>';
                    echo $this->formSelect('eh_nam_dieu_chinh', null, array('class' => 'input-small'), $nam_options);
                }
                ?>    
                <span class="help-block">Thời điểm điều chỉnh hiện tại.</span>
            </div>
        </div>

    </form>    
</div>