<h5>Quản lý cán bộ</h5>               

<?php
$list_phong_ban = array();
foreach ($this->list_phong_ban as $phong_ban) {
    $list_phong_ban[$phong_ban->pb_id] = $phong_ban->pb_name;
}

$list_chuc_vu = array();
foreach ($this->list_chuc_vu as $chuc_vu) {
    $list_chuc_vu[$chuc_vu->cv_id] = $chuc_vu->cv_name;
}
?>
<div class="main-content-box">  
    <form name="appForm" method="post" action="">
        <div class="btn-toolbar float_left">
            <div class="btn-group">
                <button class="btn" onclick="OnSubmitForm('<?php echo $this->baseUrl('tochuccanbo/employees/deleteitems/page/' . $this->arrParam['page']); ?>')"><i class="icon-trash"></i> Xóa chọn</button>
                <a class="btn" href="<?php echo $this->baseUrl('tochuccanbo/employees/search/'); ?>"><i class="icon-search"></i> Tìm kiếm</a>
                <a class="btn" href="<?php echo $this->baseUrl('tochuccanbo/employees/add/page/' . $this->arrParam['page']); ?>"><i class="icon-plus-sign"></i> Thêm mới</a>
            </div>
        </div>        
        <div class="clearfix">
        </div>
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th class="checkall_style"><input type="checkbox" name="check_all" id="checkbox" onclick="checkedAll()"></th>
                    <th style="width: 120px;">Họ & Tên đệm</th>
                    <th style="width: 90px;">Tên</th>                    
                    <th style="width: 115px;">Chức vụ</th>
                    <th style="width: 115px;">Đơn vị</th>
                    <th class="status_style">Trạng thái</th>
                    <th>Chức năng</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->paginator as $item) {
                    echo '<tr>
                            <td class="checkall_style"><input type="checkbox" name="cid[]" id="cid" value="' . $item->em_id . '"></td>
                            <td>' . $item->em_ho . ' ' . $item->em_ten_dem . '</a></td>                            
                            <td>' . $item->em_ten . '</a></td>                            
                            <td>' . $list_chuc_vu[$item->em_chuc_vu] . '</a></td>                            
                            <td>' . $list_phong_ban[$item->em_phong_ban] . '</a></td>  
                            <td class="status_style"><a href="' . ($item->em_status ? $this->baseUrl('tochuccanbo/employees/changestatus/id/' . $item->em_id . '/status/0/page/' . $this->arrParam['page']) : $this->baseUrl('tochuccanbo/employees/changestatus/id/' . $item->em_id . '/status/1/page/' . $this->arrParam['page'])) . '"><div class="' . ($item->em_status ? 'icon_status_active' : 'icon_status_inactive') . '"></div></a></td>
                            <td class="function_style">
                                <a class="btn btn-mini" href="' . $this->baseUrl('tochuccanbo/employees/edit/id/' . $item->em_id . '/page/' . $this->arrParam['page']) . '" title="Sửa"><i class="icon-edit"></i> Sửa</a>
                                <a class="btn btn-mini" href="' . $this->baseUrl('tochuccanbo/employees/delete/id/' . $item->em_id . '/page/' . $this->arrParam['page']) . '" title="Xóa"><i class="icon-trash"></i> Xóa</a>                                
                                <a class="btn btn-mini" data-toggle="modal" href="#mdHeSoLuong" title="Hệ số lương"><i class="icon-list-alt"></i> Hệ số</a>                                
                                <a class="btn btn-mini" data-toggle="modal" href="#mdLuanChuyen" title="Luân chuyển"><i class="icon-retweet"></i> Luân chuyển</a>                                
                            </td>
                        </tr>';
                }
                ?>
            </tbody>
        </table>
        <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
    </form>
</div> 

<!-- Modal -->
<div id="mdHeSoLuong" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Hệ số lương</h3>
    </div>
    <div class="modal-body">
        
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Đóng</button>
        <button class="btn btn-primary">Cập nhật</button>
    </div>
</div>

<div id="mdLuanChuyen" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Luân chuyển</h3>
    </div>
    <div class="modal-body">
        
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Đóng</button>
        <button class="btn btn-primary">Cập nhật</button>
    </div>
</div>

<script type="text/javascript">
    function loadFormHeSo(em_id){
        
    }
</script>