<div class="body_content float_right">
    <h5>Cập nhật thông tin ngạch công chức</h5>               

    <div class="main-content-box"> 
        <?php if ($this->error_message) : ?>
            <div class="alert alert-error">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <h5>Thông báo lỗi!</h5>                
                <ol>
                    <?php foreach ($this->error_message as $message): ?>
                        <li><?php echo $message; ?></li>
                    <?php endforeach; ?>
                </ol>
            </div> 
        <?php endif; ?>  
        <?php if ($this->success_message) : ?>
            <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <h5>Thông báo!</h5>
                <?php echo $this->success_message; ?>
            </div>
        <?php endif; ?>  
        <?php if ($this->ncc_info) : ?>        
            <form class="form-horizontal" method="post" action="">
                <div class="control-group">
                    <label class="control-label" for="ncc_ma_ngach">Mã nghạch</label>
                    <div class="controls">
                        <?php echo $this->formText('ncc_ma_ngach', $this->ncc_info->ncc_ma_ngach, array('required' => '')); ?>
                        <span class="help-inline">(*)</span>
                    </div>
                </div> 
                
                <div class="control-group">
                    <label class="control-label" for="ncc_name">Tên ngạch công chức</label>
                    <div class="controls">
                        <?php echo $this->formText('ncc_name', $this->ncc_info->ncc_name, array('required' => '')); ?>
                        <span class="help-inline">(*)</span>
                    </div>
                </div> 

                <div class="control-group">
                <label class="control-label" for="ncc_nam_nang_bac">Năm nâng bậc lương</label>
                <div class="controls">
                    <?php
                    $nam_options = array(1=>'1', 2=>'2', 3=>'3', 4=>'4', 5=>'5', 6=>'6', 7=>'7',8=>'8', 9=>'9', 10=>'10');                    
                    echo $this->formSelect('ncc_nam_nang_bac', $this->ncc_info->ncc_nam_nang_bac, null, $nam_options);
                    ?>                     
                </div>
            </div> 
                
                <div class="control-group">
                    <label class="control-label" for="ncc_order">Vị trí</label>
                    <div class="controls">
                        <?php echo $this->formText('ncc_order', $this->ncc_info->ncc_order, array()); ?>
                        <span class="help-block">Dùng để sắp xếp vị trí hiển thị khi dùng.</span>
                    </div>                
                </div>

                <div class="control-group">
                    <label class="control-label" for="ncc_status">Trạng thái</label>
                    <div class="controls">
                        <?php
                        $status_options = array(1 => 'Sử dụng', 0 => 'Khóa');
                        echo $this->formSelect('ncc_status', $this->ncc_info->ncc_status, null, $status_options);
                        ?>                     
                    </div>
                </div>
                <div class="control-group">
                    <div class="controls">
                        <p>
                            <button class="btn btn-small btn-primary" type="submit">Cập nhật</button>
                            <a class="btn btn-small" type="button" href="<?php echo $this->baseUrl('hethong/ngachcongchuc/index/page/' . $this->arrParam['page']); ?>">Quay lại</a>
                        </p>
                    </div>
                </div>
            </form>
        <?php else : ?>
            <form class="form-horizontal" method="post" action="">
                <div class="control-group">
                    <div class="controls">
                        <p>
                            <a class="btn btn-small" type="button" href="<?php echo $this->baseUrl('hethong/ngachcongchuc/index/page/' . $this->arrParam['page']); ?>">Quay lại</a>
                        </p>
                    </div>
                </div>
            </form>
        <?php endif; ?>        
    </div> 
</div>