<div class="body_content float_right">
    <h5>Thành viên</h5>               

    <div class="main-content-box">  
        <form name="appForm" method="post" action="">
            

            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="checkall_style"><input type="checkbox" name="check_all" id="checkbox" onclick="checkedAll()"></th>
                        <th>Tiêu đề</th>
                        <th style="width: 100px;">Ngày</th>
                        <th style="width: 100px;">Chức năng</th>
                    </tr>
                </thead>
                <tbody>
                              
                </tbody>
            </table>
        </form>
    </div>
</div>