<div class="body_content float_right">
    <h5>Thành viên</h5>               

    <div class="main-content-box">  
        <form name="appForm" method="post" action="">
            <div class="btn-toolbar float_left">
                <div class="btn-group">     
                    <button type="button" class="btn" onclick="loadFormThongBaoAll();"><i class="icon-envelope"></i> Gửi thông báo</button>
                    <input type="hidden" data-toggle="modal" href="#mdThongBao" id="btn_load_thong_bao"/>
                </div>
            </div>
            <div class="clearfix"></div>
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>    
                        <th class="checkall_style"><input type="checkbox" name="check_all" id="checkbox" onclick="checkedAll()"></th>
                        <th>Họ tên</th>
                        <th style="width: 70px;">Tên khác</th>
                        <th style="width: 100px;">Chức vụ</th>
                        <th style="width: 100px;">Ngày sinh</th>
                        <th style="width: 70px;">Giới tính</th>
                        <th style="width: 120px;">Chức năng</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($this->list_nhan_vien as $nhan_vien) {
                        ?>
                        <tr>
                            <td class="checkall_style"><input type="checkbox" name="cid[]" id="cid" value="<?php echo $nhan_vien->em_id; ?>"></td>
                            <td id="name_<?php echo $nhan_vien->em_id; ?>"><?php echo $nhan_vien->em_ho . ' ' . $nhan_vien->em_ten; ?></td>
                            <td><?php echo $nhan_vien->em_ten_khac; ?></td>
                            <td><?php echo $nhan_vien->cv_name; ?></td>
                            <td><?php echo date('d-m-Y', strtotime($nhan_vien->em_ngay_sinh)); ?></td>
                            <td><?php echo ($nhan_vien->em_gioi_tinh ? 'Nam' : 'Nữ'); ?></td>
                            <td>
                                <div class="dropdown float_left" style="padding-right: 6px;">
                                    <a class="btn btn-mini" id="drop_<?php echo $nhan_vien->em_id; ?>" role="button" data-toggle="dropdown" href="#"><i class="icon-th-list"></i> Chức năng <b class="caret"></b></a>                                    
                                    <ul id="menu1" class="dropdown-menu" role="menu" aria-labelledby="drop_<?php echo $nhan_vien->em_id; ?>">
                                        <li role="presentation">
                                            <a role="menuitem" tabindex="-1" data-toggle="modal" href="#mdThongBao" title="Gửi tin nhắn" onclick="loadFormThongBao('<?php echo $nhan_vien->em_id; ?>', '<?php echo $nhan_vien->em_ho . ' ' . $nhan_vien->em_ten; ?>')"><i class="icon-envelope"></i> Gửi thông báo</a>
                                        </li>
                                        <li role="presentation">
                                            <a role="menuitem" tabindex="-1" data-toggle="modal" href="#mdKhenThuong" title="Khen thưởng" onclick="loadFormKhenThuong('<?php echo $nhan_vien->em_id; ?>', '<?php echo $nhan_vien->em_ho . ' ' . $nhan_vien->em_ten; ?>')"><i class="icon-star"></i> Khen thưởng</a>
                                        </li>
                                        <li role="presentation">
                                            <a role="menuitem" tabindex="-1" data-toggle="modal" href="#mdKyLuat" title="Kỷ luật" onclick="loadFormKyLuat('<?php echo $nhan_vien->em_id; ?>', '<?php echo $nhan_vien->em_ho . ' ' . $nhan_vien->em_ten; ?>')"><i class="icon-exclamation-sign"></i> Kỷ luật</a>
                                        </li>
                                        <li role="presentation">
                                            <a role="menuitem" tabindex="-1" href="<?php echo $this->baseUrl('donvi/duyetchamcong'); ?>" title="Duyệt chấm công"><i class="icon-calendar"></i> Duyệt chấm công</a>
                                        </li>
                                        <li role="presentation">
                                            <a role="menuitem" tabindex="-1" href="<?php echo $this->baseUrl('donvi/duyetphanloai'); ?>" title="Duyệt phân loại cán bộ"><i class="icon-font"></i> Duyệt phân loại</a>
                                        </li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                        <?php
                    }
                    ?>
                </tbody>
            </table>
        </form>
    </div>
</div>

<div id="mdKhenThuong" class="modal_xlager hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Khen thưởng</h3>
    </div>
    <div class="modal-body" id="mdKhenThuongBody">
        <div class="alert alert-error" id="dv_khen_thuong_error" style="display: none;">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h5>Thông báo!</h5>
            Cập nhật không thành công!
        </div>

        <div class="alert alert-success" id="dv_khen_thuong_success" style="display: none;">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h5>Thông báo!</h5>
            Cập nhật thành công!
        </div>

        <form class="form-horizontal">
            <input type="hidden" id="kt_cap_nhat_id" value=""/>

            <div class="control-group">
                <label class="control-label" for="kt_ngay_khen_thuong">Ngày khen thưởng</label>
                <div class="controls">
                    <?php
                    $ngay_options = array();
                    for ($i = 1; $i <= 31; $i++) {
                        $ngay_options[$i] = $i;
                    }

                    $thang_options = array();
                    for ($i = 1; $i <= 12; $i++) {
                        $thang_options[$i] = $i;
                    }
                    $nam_options = array();
                    for ($i = 2000; $i <= 2100; $i++) {
                        $nam_options[$i] = $i;
                    }
                    echo $this->formSelect('kt_ngay_khen_thuong', date('d'), array('class' => 'input-small'), $ngay_options);
                    echo '<span class="help-inline"> / </span>';
                    echo $this->formSelect('kt_thang_khen_thuong', date('m'), array('class' => 'input-small'), $thang_options);
                    echo '<span class="help-inline"> / </span>';
                    echo $this->formSelect('kt_nam_khen_thuong', date('Y'), array('class' => 'input-small'), $nam_options);
                    ?>                    
                </div>
            </div>


            <div class="control-group">
                <label class="control-label" for="kt_can_bo">Cán bộ</label>
                <div class="controls" id="kt_can_bo">

                </div>            
            </div>
            <div class="control-group">
                <label class="control-label" for="kt_ly_do">Lý do</label>
                <div class="controls">
                    <?php echo $this->formText('kt_ly_do', null, array('class' => 'input-xxlarge', 'placeholder' => '')); ?>                   
                </div>            
            </div>
            <div class="control-group">
                <label class="control-label" for="kt_chi_tiet">Chi tiết</label>
                <div class="controls">
                    <?php echo $this->formTextarea('kt_chi_tiet', null, array('class' => 'input-xlarge', 'rows' => 5)); ?>                   
                </div>            
            </div>
            <div class="control-group">
                <label class="control-label" for="kt_money">Tiền thưởng</label>
                <div class="controls">
                    <div class="input-prepend input-append">    
                        <?php echo $this->formText('kt_money', 0, array('class' => 'input-medium', 'placeholder' => '')); ?>                    
                        <span class="add-on">VND</span>
                    </div>

                </div>            
            </div>
        </form>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Đóng</button>
        <button class="btn btn-primary" onclick="postFormKhenThuong();">Cập nhật</button>
    </div>
</div>

<div id="mdKyLuat" class="modal_xlager hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Kỷ luật/khiển trách</h3>
    </div>
    <div class="modal-body" id="mdKyLuatBody">
        <div class="alert alert-error" id="dv_ky_luat_error" style="display: none;">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h5>Thông báo!</h5>
            Cập nhật không thành công!
        </div>

        <div class="alert alert-success" id="dv_ky_luat_success" style="display: none;">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h5>Thông báo!</h5>
            Cập nhật thành công!
        </div>

        <form class="form-horizontal">
            <input type="hidden" id="kl_cap_nhat_id" value=""/>

            <div class="control-group">
                <label class="control-label" for="kl_ngay_ky_luat">Ngày kỷ luật</label>
                <div class="controls">
                    <?php
                    $ngay_options = array();
                    for ($i = 1; $i <= 31; $i++) {
                        $ngay_options[$i] = $i;
                    }

                    $thang_options = array();
                    for ($i = 1; $i <= 12; $i++) {
                        $thang_options[$i] = $i;
                    }
                    $nam_options = array();
                    for ($i = 2000; $i <= 2100; $i++) {
                        $nam_options[$i] = $i;
                    }
                    echo $this->formSelect('kl_ngay_ky_luat', date('d'), array('class' => 'input-small'), $ngay_options);
                    echo '<span class="help-inline"> / </span>';
                    echo $this->formSelect('kl_thang_ky_luat', date('m'), array('class' => 'input-small'), $thang_options);
                    echo '<span class="help-inline"> / </span>';
                    echo $this->formSelect('kl_nam_ky_luat', date('Y'), array('class' => 'input-small'), $nam_options);
                    ?>                    
                </div>
            </div>


            <div class="control-group">
                <label class="control-label" for="kl_can_bo">Cán bộ</label>
                <div class="controls" id="kl_can_bo">
                </div>            
            </div>
            <div class="control-group">
                <label class="control-label" for="kl_ly_do">Lý do</label>
                <div class="controls">
                    <?php echo $this->formText('kl_ly_do', null, array('class' => 'input-xxlarge', 'placeholder' => '')); ?>                   
                </div>            
            </div>
            <div class="control-group">
                <label class="control-label" for="kl_chi_tiet">Chi tiết</label>
                <div class="controls">
                    <?php echo $this->formTextarea('kl_chi_tiet', null, array('class' => 'input-xlarge', 'rows' => 5)); ?>                   
                </div>            
            </div>
            <div class="control-group">
                <label class="control-label" for="kl_money">Tiền phạt</label>
                <div class="controls">
                    <div class="input-prepend input-append">    
                        <?php echo $this->formText('kl_money', 0, array('class' => 'input-medium', 'placeholder' => '')); ?>                    
                        <span class="add-on">VND</span>
                    </div>

                </div>            
            </div>
        </form>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Đóng</button>
        <button class="btn btn-primary" onclick="postFormKyLuat();">Cập nhật</button>
    </div>
</div>

<div id="mdThongBao" class="modal_xlager hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Thông Báo</h3>
    </div>
    <div class="modal-body" id="mdThongBaoBody">
        <div class="alert alert-error" id="dv_thong_bao_error" style="display: none;">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h5>Thông báo!</h5>
            Cập nhật không thành công!
        </div>

        <div class="alert alert-success" id="dv_thong_bao_success" style="display: none;">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h5>Thông báo!</h5>
            Cập nhật thành công!
        </div>

        <form class="form-horizontal">
            <input type="hidden" id="tb_cap_nhat_id" value=""/>

            <div class="control-group">
                <label class="control-label" for="tb_can_bo">Người nhận</label>
                <div class="controls" id="tb_can_bo">

                </div>            
            </div>
            <div class="control-group">
                <label class="control-label" for="tb_tieu_de">Tiêu đề</label>
                <div class="controls">
                    <?php echo $this->formText('tb_tieu_de', null, array('class' => 'input-xxlarge', 'placeholder' => '')); ?>                   
                </div>            
            </div>
            <div class="control-group">
                <label class="control-label" for="tb_noi_dung">Nội dung</label>
                <div class="controls">
                    <?php echo $this->formTextarea('tb_noi_dung', null, array('class' => 'input-xlarge', 'rows' => 5)); ?>                   
                </div>            
            </div>
        </form>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Đóng</button>
        <button class="btn btn-primary" onclick="postFormThongBao();" id="btn_gui_thong_bao">Gửi thông báo</button>
    </div>
</div>

<script>
    jQuery(function($) {
      $('#kt_money').autoNumeric('init');    
      $('#kl_money').autoNumeric('init');    
    });
    function loadFormKyLuat(em_id, em_name){        
        $('#mdKyLuatBody #kl_cap_nhat_id').val(em_id);
        $('#mdKyLuatBody #kl_can_bo').html('<strong>'+em_name+'</strong>');
        tinyMCE.get('kl_chi_tiet').setContent('');
        $('#mdKyLuatBody #kl_ly_do').val('');
        $('#mdKyLuatBody #kl_money').val('0');
        $('#dv_ky_luat_success').hide();
        $('#dv_ky_luat_error').hide();
    }
    
    function postFormKyLuat(){   
        $('#dv_ky_luat_success').hide();
        $('#dv_ky_luat_error').hide();
        var em_id = $('#mdKyLuatBody #kl_cap_nhat_id').val();
        var kl_title = $('#mdKyLuatBody #kl_ly_do').val();
        var kl_content = tinyMCE.get('kl_chi_tiet').getContent();
        var kl_day = $('#mdKyLuatBody #kl_ngay_ky_luat').val();
        var kl_month = $('#mdKyLuatBody #kl_thang_ky_luat').val();
        var kl_year = $('#mdKyLuatBody #kl_nam_ky_luat').val();   
        //var kl_money = $('#mdKyLuatBody #kl_money').val();   
        var kl_money = $('#mdKyLuatBody #kl_money').autoNumeric('get');   
        if(kl_title !='' && kl_content!=''){
            $.post( site_url+'/donvi/thanhvien/jqkyluat', {
                em_id: em_id, 
                kl_date_day: kl_day, 
                kl_date_month: kl_month,
                kl_date_year: kl_year,
                kl_money: kl_money,
                kl_ly_do: kl_title,
                kl_chi_tiet: kl_content
            }, function(data) {
                if(data.status){
                    $('#dv_ky_luat_success').show();
                    tinyMCE.get('kl_chi_tiet').setContent('');
                    $('#mdKyLuatBody #kl_ly_do').val('');
                }else{
                    $('#dv_ky_luat_error').show();
                }
            }, 'json');
        }else{
            alert('Bạn phải nhập đầy đủ lý do và nội dung kỷ luật!');
        }
    }
    
    function loadFormKhenThuong(em_id, em_name){        
        $('#mdKhenThuongBody #kt_cap_nhat_id').val(em_id);
        $('#mdKhenThuongBody #kt_can_bo').html('<strong>'+em_name+'</strong>');
        tinyMCE.get('kt_chi_tiet').setContent('');
        $('#mdKhenThuongBody #kt_ly_do').val('');
        $('#mdKhenThuongBody #kt_money').val('0');
        $('#dv_khen_thuong_success').hide();
        $('#dv_khen_thuong_error').hide();
    }
    
    function postFormKhenThuong(){   
        $('#dv_khen_thuong_success').hide();
        $('#dv_khen_thuong_error').hide();
        var em_id = $('#mdKhenThuongBody #kt_cap_nhat_id').val();
        var kt_title = $('#mdKhenThuongBody #kt_ly_do').val();
        var kt_content = tinyMCE.get('kt_chi_tiet').getContent();
        var kt_day = $('#mdKhenThuongBody #kt_ngay_khen_thuong').val();
        var kt_month = $('#mdKhenThuongBody #kt_thang_khen_thuong').val();
        var kt_year = $('#mdKhenThuongBody #kt_nam_khen_thuong').val(); 
        //var kt_money = $('#mdKhenThuongBody #kt_money').val(); 
        var kt_money = $('#mdKhenThuongBody #kt_money').autoNumeric('get');
        
        if(kt_title !='' && kt_content!=''){
            $.post( site_url+'/donvi/thanhvien/jqkhenthuong', { 
                em_id: em_id, 
                kt_date_day: kt_day, 
                kt_date_month: kt_month,
                kt_date_year: kt_year,
                kt_money: kt_money,
                kt_ly_do: kt_title,
                kt_chi_tiet: kt_content
            }, function( data ) {
                if(data.status){
                    $('#dv_khen_thuong_success').show();
                    tinyMCE.get('kt_chi_tiet').setContent('');
                    $('#mdKhenThuongBody #kt_ly_do').val('');
                }else{
                    $('#dv_khen_thuong_error').show();
                }
            }, 'json');
        }else{
            alert('Bạn phải nhập đầy đủ lý do và nội dung khen thưởng!');
        }
    }
    
    function loadFormThongBaoAll(){
        var em_id = '';
        var em_name = '';
        $( "input:checkbox[name='cid[]']" ).each(function( index ) {            
            if($(this).is(':checked')){
                var c_id = $(this).val();
                em_id +=c_id+', ';
                em_name +=$('#name_'+c_id).html()+',';
            }
        });  
        if(em_id !==''){
            loadFormThongBao(em_id,em_name);
            $('#btn_load_thong_bao').click();
        }else{
            alert('Bạn phải chọn ít nhất một thành viên nhận thông báo!');
        }
    }
    
    function loadFormThongBao(em_id, em_name){        
        $('#mdThongBaoBody #tb_cap_nhat_id').val(em_id);
        $('#mdThongBaoBody #tb_can_bo').html('<strong>'+em_name+'</strong>');
        tinyMCE.get('tb_noi_dung').setContent('');
        $('#mdThongBaoBody #tb_tieu_de').val('');
        $('#dv_thong_bao_success').hide();
        $('#dv_thong_bao_error').hide();
    }
    
    function postFormThongBao(){                
        $('#dv_thong_bao_success').hide();
        $('#dv_thong_bao_error').hide();
        var em_id = $('#mdThongBaoBody #tb_cap_nhat_id').val();
        var tb_title = $('#mdThongBaoBody #tb_tieu_de').val();
        var tb_content = tinyMCE.get('tb_noi_dung').getContent();
        if(tb_title !='' && tb_content!=''){
            $("#btn_gui_thong_bao").attr("disabled", "disabled");
            $.post( site_url+'/canhan/thongbao/jqnewtb', {
                em_id: em_id, 
                tb_title: tb_title, 
                tb_content: tb_content
            }, function(data) {    
                $("#btn_gui_thong_bao").removeAttr("disabled");
                if(data.status){
                    $('#dv_thong_bao_success').show();
                    tinyMCE.get('tb_noi_dung').setContent('');
                    $('#mdThongBaoBody #tb_tieu_de').val('');
                }else{
                    $('#dv_thong_bao_error').show();
                }
            }, 'json');
        }else{
            alert('Bạn phải nhập đầy đủ tiêu đề và nội dung!');
        }        
    }
</script>