
<h5>Quản lý hệ số 0.2</h5>               

<div class="main-content-box">  
    <form name="appForm" method="post" action="">
        <div class="btn-toolbar float_left">
            <div class="btn-group">
                <button type="button" class="btn" onclick="OnSubmitForm('<?php echo $this->baseUrl('taivu/heso02/deleteitems/page/' . $this->arrParam['page']); ?>')"><i class="icon-trash"></i> Xóa chọn</button>
                <a class="btn" href="<?php echo $this->baseUrl('taivu/heso02/add/page/' . $this->arrParam['page']); ?>"><i class="icon-plus-sign"></i> Thêm mới</a>
            </div>
        </div>
        <div class="clearfix">
        </div>
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th class="checkall_style" rowspan="2"><input type="checkbox" name="check_all" id="checkbox" onclick="checkedAll()"></th>
                    <th rowspan="2">Năm</th>  
                    <th class="order_style" colspan="12"><center>Tháng</center></th>
            <th class="function_style" rowspan="2"><center>Chức năng</center></th>
            </tr>
            <tr>
                <th>1</th>
                <th>2</th>
                <th>3</th>
                <th>4</th>
                <th>5</th>
                <th>6</th>
                <th>7</th>
                <th>8</th>
                <th>9</th>
                <th>10</th>
                <th>11</th>
                <th>12</th>
            </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->paginator as $item) {
                    ?>
                    <tr>
                        <td class="checkall_style"><input type="checkbox" name="cid[]" id="cid" value="<?php echo $item->id;?>"></td>
                        <td><a href="<?php echo $this->baseUrl('taivu/heso02/edit/id/' . $item->id . '/page/' . $this->arrParam['page']);?>"><?php echo $item->nam;?></a></td>                            
                        <td><?php echo $item->thang_1;?></td>                        
                        <td><?php echo $item->thang_2;?></td>                        
                        <td><?php echo $item->thang_3;?></td>                        
                        <td><?php echo $item->thang_4;?></td>                        
                        <td><?php echo $item->thang_5;?></td>                        
                        <td><?php echo $item->thang_6;?></td>                        
                        <td><?php echo $item->thang_7;?></td>                        
                        <td><?php echo $item->thang_8;?></td>                        
                        <td><?php echo $item->thang_9;?></td>                        
                        <td><?php echo $item->thang_10;?></td>                        
                        <td><?php echo $item->thang_11;?></td>                        
                        <td><?php echo $item->thang_12;?></td>                           
                        <td class="function_style">
                                <a class="btn btn-mini" href="<?php echo $this->baseUrl('taivu/heso02/edit/id/' . $item->id . '/page/' . $this->arrParam['page']);?>" title="Sửa"><i class="icon-edit"></i> Sửa</a>
                                <a class="btn btn-mini" href="<?php echo $this->baseUrl('taivu/heso02/delete/id/' . $item->id . '/page/' . $this->arrParam['page']);?>" title="Xóa"><i class="icon-trash"></i> Xóa</a>                                
                        </td>
                    </tr>

                <?php }; ?>
            </tbody>
        </table>
        <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
    </form>
</div> 