<h5>Quản lý yêu cầu cập nhật thông tin</h5>               

<?php
$list_phong_ban = array();
foreach ($this->list_phong_ban as $phong_ban) {
    $list_phong_ban[$phong_ban->pb_id] = $phong_ban->pb_name;
}

$list_phong_ban_options = array('0' => 'Tất cả');
foreach ($this->list_phong_ban_option as $phong_ban) {
    $list_phong_ban_options[$phong_ban->pb_id] = $phong_ban->pb_name;
}

$list_chuc_vu = array();
foreach ($this->list_chuc_vu as $chuc_vu) {
    $list_chuc_vu[$chuc_vu->cv_id] = $chuc_vu->cv_name;
}
?>
<div class="main-content-box">  
    <form name="appForm" method="post" action="">
        <div class="btn-toolbar float_left">
            <div class="btn-group">
                <button class="btn" onclick="OnSubmitForm('<?php echo $this->baseUrl('tochuccanbo/employees/deleteitems/page/' . $this->arrParam['page']); ?>')"><i class="icon-trash"></i> Xóa chọn</button>
            </div>
        </div>   
        <div class="btn-toolbar form-search float_right text-right">
            <?php
            echo $this->formSelect('sl_phong_ban', $this->pb_id, array('onchange' => 'on_choose_phong_ban()'), $list_phong_ban_options);
            ?> 
        </div>
        <div class="clearfix">
        </div>
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th class="checkall_style"><input type="checkbox" name="check_all" id="checkbox" onclick="checkedAll()"></th>
                    <th>Họ & Tên đệm</th>
                    <th>Tên</th>                    
                    <th>Chức vụ</th>
                    <th>Đơn vị</th>
                    <th>Ngày yêu cầu</th>
                    <th>Chức năng</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->paginator as $item) {
                    $employee_info = $this->viewGetEmployeeInfo($item->em_id);
                    if ($employee_info) {
                        echo '<tr>
                                <td class="checkall_style"><input type="checkbox" name="cid[]" id="cid" value="' . $item->eme_id . '"></td>
                                <td>' . $employee_info->em_ho . '</a></td>                            
                                <td>' . $employee_info->em_ten . '</a></td>                            
                                <td>' . $list_chuc_vu[$employee_info->em_chuc_vu] . '</a></td>                            
                                <td>' . $list_phong_ban[$employee_info->em_phong_ban] . '</a></td>  
                                <td>' . date('d-m-d h:m', strtotime($item->eme_date_modified)) . '</td>  
                                
                                <td class="function_style">
                                    <a class="btn btn-mini" href="' . $this->baseUrl('tochuccanbo/capnhatthongtin/chitiet/id/' . $item->eme_id . '/page/' . $this->arrParam['page']) . '" title="Sửa"><i class="icon-edit"></i> Chi tiết</a>
                                    <a class="btn btn-mini" href="' . $this->baseUrl('tochuccanbo/capnhatthongtin/delete/id/' . $item->eme_id . '/page/' . $this->arrParam['page']) . '" title="Xóa"><i class="icon-trash"></i> Xóa</a>                                
                                </td>
                            </tr>';
                    }
                }
                ?>
            </tbody>
        </table>
        <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
    </form>
</div> 

<script>
    function on_choose_phong_ban(){
        var phong_ban = $('#sl_phong_ban').val();
        window.location = site_url+'/tochuccanbo/capnhatthongtin/index/phongban/'+phong_ban;
    }
</script>