<div class="body_content float_right">
    <h5>Thông báo mới</h5>               

    <div class="main-content-box">                     
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Tiêu đề</th>
                    <th>Ngày</th>
                    <th>Chức năng</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td><a>Thông báo về việc cập nhật hồ sơ</a></td>
                    <td>29/12/2013</td>
                    <td>
                        <a class="btn btn-mini" href="#" title="Xem"><i class="icon-play"></i></a>
                        <a class="btn btn-mini" href="#" title="Đánh dấu đã xem"><i class="icon-eye-open"></i></a>
                        <a class="btn btn-mini" href="#" title="Xóa"><i class="icon-trash"></i></a>
                    </td>
                </tr>  
                <tr>
                    <td>2</td>
                    <td><a>Thông báo về việc cập nhật hồ sơ</a></td>
                    <td>29/12/2013</td>
                    <td>
                        <a class="btn btn-mini" href="#" title="Xem"><i class="icon-play"></i></a>
                        <a class="btn btn-mini" href="#" title="Đánh dấu đã xem"><i class="icon-eye-open"></i></a>
                        <a class="btn btn-mini" href="#" title="Xóa"><i class="icon-trash"></i></a>
                    </td>
                </tr>  
                <tr>
                    <td>3</td>
                    <td><a>Thông báo về việc cập nhật hồ sơ</a></td>
                    <td>29/12/2013</td>
                    <td>
                        <a class="btn btn-mini" href="#" title="Xem"><i class="icon-play"></i></a>
                        <a class="btn btn-mini" href="#" title="Đánh dấu đã xem"><i class="icon-eye-open"></i></a>
                        <a class="btn btn-mini" href="#" title="Xóa"><i class="icon-trash"></i></a>
                    </td>
                </tr>  
                <tr>
                    <td>4</td>
                    <td><a>Thông báo về việc cập nhật hồ sơ</a></td>
                    <td>29/12/2013</td>
                    <td>
                        <a class="btn btn-mini" href="#" title="Xem"><i class="icon-play"></i></a>
                        <a class="btn btn-mini" href="#" title="Đánh dấu đã xem"><i class="icon-eye-open"></i></a>
                        <a class="btn btn-mini" href="#" title="Xóa"><i class="icon-trash"></i></a>
                    </td>
                </tr>  
            </tbody>
        </table>
    </div> 
</div>