<h5>Thông tin cá nhân</h5>               

<div class="main-content-box">                     
    Họ tên:  <em>Nguyễn Mạnh Hùng </em><br>
    Ngày sinh: <em>07/10/1986</em><br>
    Chức vụ: <em>Projects Manager</em><br>
    Địa chỉ: <em>174 Khuất Duy Tiến, Thanh Xuân, Hà Nội</em><br>                      
    <abbr title="Phone">P:</abbr><em> (123) 456-7890</em>
</div>

<h5>Thông báo mới</h5>               

<div class="main-content-box">                     
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>ID</th>
                <th>Tiêu đề</th>
                <th>Ngày</th>
                <th>Chức năng</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td><a>Thông báo về việc cập nhật hồ sơ</a></td>
                <td>29/12/2013</td>
                <td>
                    <a class="btn btn-mini" href="#" title="Xem"><i class="icon-play"></i></a>
                    <a class="btn btn-mini" href="#" title="Đánh dấu đã xem"><i class="icon-eye-open"></i></a>
                    <a class="btn btn-mini" href="#" title="Xóa"><i class="icon-trash"></i></a>
                </td>
            </tr>  
            <tr>
                <td>2</td>
                <td><a>Thông báo về việc cập nhật hồ sơ</a></td>
                <td>29/12/2013</td>
                <td>
                    <a class="btn btn-mini" href="#" title="Xem"><i class="icon-play"></i></a>
                    <a class="btn btn-mini" href="#" title="Đánh dấu đã xem"><i class="icon-eye-open"></i></a>
                    <a class="btn btn-mini" href="#" title="Xóa"><i class="icon-trash"></i></a>
                </td>
            </tr>  
            <tr>
                <td>3</td>
                <td><a>Thông báo về việc cập nhật hồ sơ</a></td>
                <td>29/12/2013</td>
                <td>
                    <a class="btn btn-mini" href="#" title="Xem"><i class="icon-play"></i></a>
                    <a class="btn btn-mini" href="#" title="Đánh dấu đã xem"><i class="icon-eye-open"></i></a>
                    <a class="btn btn-mini" href="#" title="Xóa"><i class="icon-trash"></i></a>
                </td>
            </tr>  
            <tr>
                <td>4</td>
                <td><a>Thông báo về việc cập nhật hồ sơ</a></td>
                <td>29/12/2013</td>
                <td>
                    <a class="btn btn-mini" href="#" title="Xem"><i class="icon-play"></i></a>
                    <a class="btn btn-mini" href="#" title="Đánh dấu đã xem"><i class="icon-eye-open"></i></a>
                    <a class="btn btn-mini" href="#" title="Xóa"><i class="icon-trash"></i></a>
                </td>
            </tr>  
        </tbody>
    </table>
</div> 

<h5>Liên kết nhanh</h5>               

<div class="main-content-box">                     
    <p>
        <button class="btn btn-small" type="button"><i class="icon-list-alt"></i> Thông báo</button>
        <button class="btn btn-small" type="button"><i class="icon-hand-up"></i> Chấm công</button>
        <button class="btn btn-small" type="button"><i class="icon-time"></i> Khai báo làm ngoài giờ</button>
        <button class="btn btn-small" type="button"><i class="icon-flag"></i> Xin nghỉ phép</button>
        <button class="btn btn-small" type="button"><i class="icon-hand-up"></i> Chấm công</button>
        <button class="btn btn-small" type="button"><i class="icon-hand-up"></i> Chấm công</button>
    </p>
</div>