<div class="body_content float_right">
    <h5>Quản lý nhóm, phân quyền</h5>               

    <div class="main-content-box">  
        <form name="appForm" method="post" action="">
            <div class="btn-toolbar float_left">
                <div class="btn-group">
                    <button class="btn" onclick="OnSubmitForm('<?php echo $this->baseUrl('hethong/groups/deleteitems/page/'.$this->arrParam['page']); ?>')"><i class="icon-trash"></i> Xóa chọn</button>
                    <a class="btn" href="<?php echo $this->baseUrl('hethong/groups/add/page/' . $this->arrParam['page']); ?>"><i class="icon-plus-sign"></i> Thêm nhóm mới</a>
                </div>
            </div>
            <div class="btn-toolbar form-search float_right text-right">
                <input type="text" name="skw" value="<?php echo $this->arrParam['kw']; ?>" placeholder="Tên nhóm" class="input-medium search-query" onkeypress="return removeEnterKeyPress(event);">
                <button type="submit" class="btn" onclick="OnSubmitFormSearch('<?php echo $this->baseUrl('hethong/groups/search/kw/'); ?>')">Tìm kiếm</button>
            </div>
            <div class="clearfix">
            </div>
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="checkall_style"><input type="checkbox" name="check_all" id="checkbox" onclick="checkedAll()"></th>
                        <th>Tên nhóm</th>
                        <th class="status_style">Trạng thái</th>
                        <th class="function_style">Chức năng</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($this->list_groups as $group) {
                        echo '<tr>
                            <td class="checkall_style"><input type="checkbox" name="cid[]" id="cid" value="' . $group->group_id . '"></td>
                            <td><a href="' . $this->baseUrl('hethong/groups/edit/id/' . $group->group_id . '/page/' . $this->arrParam['page']) . '">' . $group->group_name . '</a></td>
                            <td class="status_style"><a href="' . ($group->group_status ? $this->baseUrl('hethong/groups/changestatus/id/' . $group->group_id . '/status/0/page/' . $this->arrParam['page']) : $this->baseUrl('hethong/groups/changestatus/id/' . $group->group_id . '/status/1/page/' . $this->arrParam['page'])) . '"><div class="' . ($group->group_status ? 'icon_status_active' : 'icon_status_inactive') . '"></div></a></td>
                            <td class="function_style">
                                <a class="btn btn-mini" href="' . $this->baseUrl('hethong/groups/edit/id/' . $group->group_id . '/page/' . $this->arrParam['page']) . '" title="Sửa"><i class="icon-edit"></i> Sửa</a>
                                <a class="btn btn-mini" href="' . $this->baseUrl('hethong/groups/delete/id/' . $group->group_id . '/page/' . $this->arrParam['page']) . '" title="Xóa"><i class="icon-trash"></i> Xóa</a>
                                <a class="btn btn-mini" href="' . $this->baseUrl('hethong/groups/permissions/id/' . $group->group_id . '/page/' . $this->arrParam['page']) . '" title="Phân quyền"><i class="icon-cog"></i> Phân Quyền</a>
                            </td>
                        </tr>';
                    }
                    ?>
                </tbody>
            </table>
        </form>
    </div> 
</div>