<div class="body_content float_right">
    <h5>Thông báo</h5>               

    <div class="main-content-box">  
        <?php if (!$this->thong_bao) { ?>
            <strong>Không tìm thấy nội dung.</strong><br>
            <form class="form-horizontal" method="post" action="">
                <div class="control-group">
                    <div class="controls">
                        <p>
                            <a class="btn btn-small" type="button" href="<?php echo $this->baseUrl('canhan/thongbao/index/page/' . $this->page); ?>">Quay lại</a>
                        </p>
                    </div>
                </div>
            </form>

        <?php } else {
            ?>

            <address>
                <strong><?php echo $this->thong_bao['tb_tieu_de']; ?></strong><br>
                <?php
                $name = 'Hệ thống';
                $phong_ban = '';
                if ($this->thong_bao['tb_from']) {
                    $name = $this->thong_bao['em_ho'] . ' ' . $this->thong_bao['em_ten_dem'] . ' ' . $this->thong_bao['em_ten'];
                    $phong_ban = 'Phòng: ' . $this->viewGetPhongBanName($this->thong_bao['em_phong_ban']) . '<br>';
                }
                ?>
                Người gửi: <?php echo $name; ?><br>
                <?php echo $phong_ban; ?>
            </address>

            <address>
                <?php echo $this->thong_bao['tb_noi_dung']; ?>
            </address>

            <form class="form-horizontal" method="post" action="">
                <?php echo $this->formHidden('id', $this->thong_bao['tb_id']); ?>
                <div class="control-group">
                    <div class="controls">
                        <p>
                            Bạn có chắc chắn muốn xóa?</strong>
                        </p>
                    </div>
                </div>
                <div class="control-group">
                    <div class="controls">
                        <p>
                            <button name="del" value="Yes" class="btn btn-small btn-primary" type="submit">Đồng ý xóa</button>
                            <a class="btn btn-small" type="button" href="<?php echo $this->baseUrl('canhan/thongbao/index/page/' . $this->page); ?>">Quay lại</a>
                        </p>
                    </div>
                </div>
            </form>

            <?php
        }
        ?>
    </div>
</div>