<div class="body_content float_right">
    <h5>Thông báo</h5>               

    <div class="main-content-box">  
        <form name="appForm" method="post" action="">
            <div class="btn-toolbar float_left">
                <div class="btn-group">
                    <button class="btn" onclick="OnSubmitForm('<?php echo $this->baseUrl('canhan/thongbao/deleteitems/page/' . $this->arrParam['page']); ?>')"><i class="icon-trash"></i> Xóa chọn</button>
                </div>
            </div>

            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="checkall_style"><input type="checkbox" name="check_all" id="checkbox" onclick="checkedAll()"></th>
                        <th>Tiêu đề</th>
                        <th style="width: 100px;">Ngày</th>
                        <th style="width: 100px;">Chức năng</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if (!sizeof($this->list_thong_bao)) {
                        echo '<tr><td colspan="4">Không có thông báo mới</td></tr>';
                    } else {
                        $i = 0;
                        foreach ($this->list_thong_bao as $thong_bao) {
                            $i++;
                            $class_row = '';
                            if (!$thong_bao->tb_status) {
                                $class_row = "not_yet_read";
                            }
                            echo '<tr id="row_' . $thong_bao->tb_id . '" class="' . $class_row . '">
                            <td class="checkall_style"><input type="checkbox" name="cid[]" id="cid" value="' . $thong_bao->tb_id . '"></td>
                            <td><a href="' . $this->baseUrl('canhan/thongbao/view/id/' . $thong_bao->tb_id) . '">' . $thong_bao->tb_tieu_de . '</a></td>
                            <td>' . date('d-m-Y', strtotime($thong_bao->tb_date_added)) . '</td>
                            <td>
                                <a class="btn btn-mini" href="' . $this->baseUrl('canhan/thongbao/view/id/' . $thong_bao->tb_id . '/page/' . $this->page) . '" title="Xem"><i class="icon-play"></i></a>
                                <a class="btn btn-mini" role="button" data-toggle="modal" href="#mdTBDelete_' . $thong_bao->tb_id . '" title="Xóa"><i class="icon-trash"></i></a>
                                    <div id="mdTBDelete_' . $thong_bao->tb_id . '" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                    <div class="modal-header">
                                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                      <h3 id="myModalLabel">Xác nhận</h3>
                                    </div>
                                    <div class="modal-body">
                                      <p>Bạn có chắc chắn muốn xóa</p>
                                    </div>
                                    <div class="modal-footer">
                                      <button class="btn" data-dismiss="modal" aria-hidden="true">Không xóa</button>
                                      <button class="btn btn-danger" data-dismiss="modal" aria-hidden="true" onclick="delete_thong_bao(' . $thong_bao->tb_id . ')">Xóa</button>
                                    </div>
                                  </div>
                            </td>
                        </tr>';
                        }
                    }
                    ?>             
                </tbody>
            </table>
        </form>
    </div>
</div>

<script>
    function delete_thong_bao(id){
        $.post( site_url+"/canhan/thongbao/jqdelete/", { tb_id: id},function( data ) {
            if(data.status){
                $('#row_'+id).remove();
            }            
        }, 'json');
    }
</script>