<h5>Quản lý khen thưởng</h5>               

<div class="main-content-box">  
    <form name="appForm" class="form-horizontal" method="post" action="">
        <div class="control-group">
            <label class="control-label">Tháng</label>
            <div class="controls">
                <div class="input-append">
                    <input class="span2" value="<?php echo $this->thang . '/' . $this->nam; ?>" id="txt_thang_nam" type="text" readonly="true"/>
                    <button class="btn" type="button" id="btn_chon_thang">Chọn tháng!</button>
                </div>

            </div>
        </div>

        <div class="clearfix">
        </div>
        <div class="btn-toolbar float_left">
            <div class="btn-group">
                <button class="btn" onclick="OnSubmitForm('<?php echo $this->baseUrl('tochuccanbo/khenthuong/updatestatus/status/1/thang/' . $this->thang . '/nam/' . $this->nam); ?>')"><i class="icon-ok-sign"></i> Đồng ý</button>
                <button class="btn" onclick="OnSubmitForm('<?php echo $this->baseUrl('tochuccanbo/khenthuong/updatestatus/status/0/thang/' . $this->thang . '/nam/' . $this->nam); ?>')"><i class="icon-ban-circle"></i> Không đồng ý</button>
            </div>
        </div>
        <div class="clearfix">
        </div>
        
        <table class="table table-bordered table-hover">
            <thead>
                <tr>  
                    <th class="checkall_style"><input type="checkbox" name="check_all" id="checkbox" onclick="checkedAll()"></th>
                    <th>Họ tên</th>
                    <th style="width: 120px;">Đơn vị</th>
                    <th style="width: 250px;">Lý do</th>
                    <th style="width: 100px;">Ngày</th>
                    <th style="width: 110px;">Trạng thái</th>
                    <th style="width: 120px;">Chức năng</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->list_khen_thuong as $item) {
                    $trang_thai_icon = 'Không đồng ý';
                    if($item->kt_don_vi && !$item->kt_don_vi->kt_ptccb_viewed){
                        $trang_thai_icon = 'Chờ duyệt';
                    }
                    
                    if($item->kt_status){
                        $trang_thai_icon = 'Đồng ý';
                    }else{
                        if($item->kt_ptccb_viewed)
                            $trang_thai_icon = 'Không đồng ý';
                    }
                    
                    
                    $phong_ban_name = $this->viewGetPhongBanName($item->em_phong_ban);
                    ?>
                    <tr id="name_<?php echo $item->kt_id; ?>">
                        <td class="checkall_style"><input type="checkbox" name="cid[]" id="cid" value="<?php echo $item->kt_id; ?>"></td>
                        <td><?php echo $item->em_ho . ' ' . $item->em_ten; ?></td>
                        <td><?php echo $phong_ban_name; ?></td>
                        <td><?php echo $item->kt_ly_do; ?><span id="hd_kt_chi_tiet_<?php echo $item->kt_id; ?>" class="hide"><?php echo $item->kt_chi_tiet; ?></span></td>
                        <td><?php echo date('d-m-Y', strtotime($item->kt_date)); ?></td>
                        <td><span id="trang_thai_<?php echo $item->kt_id; ?>"><?php echo $trang_thai_icon; ?></span></td>
                        <td>
                            <div class="dropdown float_left" style="padding-right: 6px;">
                                <a class="btn btn-mini" id="drop_<?php echo $item->kt_id; ?>" role="button" data-toggle="dropdown" href="#"><i class="icon-th-list"></i> Chức năng <b class="caret"></b></a>                                    
                                <ul id="menu1" class="dropdown-menu" role="menu" aria-labelledby="drop_<?php echo $item->kt_id; ?>">
                                    <li role="presentation">
                                        <a role="menuitem" tabindex="-1" data-toggle="modal" href="#mdChiTiet<?php echo $item->kt_id; ?>" title="Xem chi tiết"><i class="icon-align-justify"></i> Xem chi tiết</a>
                                    </li>                                    
                                    <li role="presentation">
                                        <a role="menuitem" tabindex="-1" data-toggle="modal" href="#mdKhenThuong" title="Sửa nội dung" onclick="loadFormKhenThuong(<?php echo $item->kt_id; ?>,<?php echo date('d', strtotime($item->kt_date)); ?>, <?php echo date('m', strtotime($item->kt_date)); ?>, <?php echo date('Y', strtotime($item->kt_date)); ?>, '<?php echo $item->em_ho . ' ' . $item->em_ten; ?>', '<?php echo $item->kt_ly_do; ?>', <?php echo $item->kt_money; ?>)"><i class="icon-edit"></i> Sửa nội dung</a>
                                    </li>                                    
                                    <li role="presentation">
                                        <a role="menuitem" tabindex="-1" onclick="update_status(<?php echo $item->kt_id; ?>, 1)" title="Đồng ý"><i class="icon-ok-circle"></i> Đồng ý</a>
                                    </li>                                    
                                    <li role="presentation">
                                        <a role="menuitem" tabindex="-1" onclick="update_status(<?php echo $item->kt_id; ?>, 0)" title="Không đồng ý"><i class="icon-ban-circle"></i> Không đồng ý</a>
                                    </li>                                    
                                </ul>
                            </div>
                            <div id="mdChiTiet<?php echo $item->kt_id; ?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                    <h3 id="myModalLabel">Chi tiết</h3>
                                </div>
                                <div class="modal-body">
                                    <div class="row">
                                        <div class="span4 float_left"><strong>Nhân viên: </strong> <?php echo $item->em_ho . ' ' . $item->em_ten; ?></div>
                                    </div>
                                    <div class="row">
                                        <div class="span4 float_left"><strong>Phòng ban: </strong> <?php echo $phong_ban_name; ?></div>
                                    </div>
                                    <div class="row">
                                        <div class="span4 float_left"><strong>Lý do: </strong> <?php echo $item->kt_ly_do; ?></div>
                                    </div>
                                    <div class="row">
                                        <div class="span4 float_left"><strong>Nội dung: </strong> <?php echo $item->kt_chi_tiet; ?></div>
                                    </div>
                                    <div class="row">
                                        <div class="span4 float_left"><strong>Ngày khen thưởng: </strong> <?php echo date('d-m-Y', strtotime($item->kt_date)); ?></div>
                                    </div>
                                    <div class="row">
                                        <div class="span4 float_left"><strong>Mức khen thưởng: </strong> <?php echo number_format($item->kt_money, 0, '.', ','); ?>VND</div>
                                    </div>

                                </div>
                                <div class="modal-footer">
                                    <button class="btn btn-primary" data-toggle="modal" href="#mdKhenThuong" title="Sửa nội dung" onclick="loadFormKhenThuong(<?php echo $item->kt_id; ?>,<?php echo date('d', strtotime($item->kt_date)); ?>, <?php echo date('m', strtotime($item->kt_date)); ?>, <?php echo date('Y', strtotime($item->kt_date)); ?>, '<?php echo $item->em_ho . ' ' . $item->em_ten; ?>', '<?php echo $item->kt_ly_do; ?>', <?php echo $item->kt_money; ?>)">Sửa nội dung</button>
                                    <button class="btn btn-success" type="button" onclick="update_status(<?php echo $item->kt_id; ?>, 1)">Đồng ý</button>
                                    <button class="btn btn-danger" type="button" onclick="update_status(<?php echo $item->kt_id; ?>, 0)">Không đồng ý</button>
                                    <button class="btn" data-dismiss="modal" aria-hidden="true">Đóng</button>
                                </div>
                            </div>

                        </td>
                    </tr>
                    <?php
                }
                ?>
            </tbody>
        </table>
    </form>
</div>

<div id="mdKhenThuong" class="modal_xlager hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Khen thưởng</h3>
    </div>
    <div class="modal-body" id="mdKhenThuongBody">
        <div class="alert alert-error" id="dv_khen_thuong_error" style="display: none;">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h5>Thông báo!</h5>
            Cập nhật không thành công!
        </div>

        <div class="alert alert-success" id="dv_khen_thuong_success" style="display: none;">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h5>Thông báo!</h5>
            Cập nhật thành công!
        </div>

        <form class="form-horizontal">
            <input type="hidden" id="kt_cap_nhat_id" value=""/>

            <div class="control-group">
                <label class="control-label" for="kt_ngay_khen_thuong">Ngày khen thưởng</label>
                <div class="controls">
                    <?php
                    $ngay_options = array();
                    for ($i = 1; $i <= 31; $i++) {
                        $ngay_options[$i] = $i;
                    }

                    $thang_options = array();
                    for ($i = 1; $i <= 12; $i++) {
                        $thang_options[$i] = $i;
                    }
                    $nam_options = array();
                    for ($i = 2000; $i <= 2100; $i++) {
                        $nam_options[$i] = $i;
                    }
                    echo $this->formSelect('kt_ngay_khen_thuong', date('d'), array('class' => 'input-small'), $ngay_options);
                    echo '<span class="help-inline"> / </span>';
                    echo $this->formSelect('kt_thang_khen_thuong', date('m'), array('class' => 'input-small'), $thang_options);
                    echo '<span class="help-inline"> / </span>';
                    echo $this->formSelect('kt_nam_khen_thuong', date('Y'), array('class' => 'input-small'), $nam_options);
                    ?>                    
                </div>
            </div>


            <div class="control-group">
                <label class="control-label" for="kt_can_bo">Cán bộ</label>
                <div class="controls" id="kt_can_bo">

                </div>            
            </div>
            <div class="control-group">
                <label class="control-label" for="kt_ly_do">Lý do</label>
                <div class="controls">
                    <?php echo $this->formText('kt_ly_do', null, array('class' => 'input-xxlarge', 'placeholder' => '')); ?>                   
                </div>            
            </div>
            <div class="control-group">
                <label class="control-label" for="kt_chi_tiet">Chi tiết</label>
                <div class="controls">
                    <?php echo $this->formTextarea('kt_chi_tiet', null, array('class' => 'input-xlarge', 'rows' => 5)); ?>                   
                </div>            
            </div>
            <div class="control-group">
                <label class="control-label" for="kt_money">Tiền thưởng</label>
                <div class="controls">
                    <div class="input-prepend input-append">    
                        <?php echo $this->formText('kt_money', 0, array('class' => 'input-medium', 'placeholder' => '')); ?>                    
                        <span class="add-on">VND</span>
                    </div>

                </div>            
            </div>
        </form>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Đóng</button>
        <button class="btn btn-primary" onclick="postFormKhenThuong();">Chấp nhận</button>
    </div>
</div>

<script>
    var currentYear = <?php echo $this->nam; ?>;    
    var options = {
        pattern: 'mm/yyyy', // Default is 'mm/yyyy' and separator char is not mandatory 
        startYear: 2013,
        selectedYear: currentYear,
        monthNames: ['Tháng 1', 'Tháng 2', 'Tháng 3', 'Tháng 4', 'Tháng 5', 'Tháng 6', 'Tháng 7', 'Tháng 8', 'Tháng 9', 'Tháng 10', 'Tháng 11', 'Tháng 12']
    };

    $('#txt_thang_nam').monthpicker(options);

    $('#txt_thang_nam').monthpicker().bind('monthpicker-click-month', function (e, month, year) { 
        window.location = site_url+'/tochuccanbo/khenthuong/index/thang/'+month+'/nam/'+year;
    });

    $('#btn_chon_thang').bind('click', function () {
        $('#txt_thang_nam').monthpicker('show');
    });
    
    jQuery(function($) {
      $('#mdKhenThuongBody #kt_money').autoNumeric('init');   
    });
    
    function loadFormKhenThuong(kt_id, ngay, thang, nam, em_name, ly_do, money){ 
        var chi_tiet = $('#hd_kt_chi_tiet_'+kt_id).html();
        $('#mdChiTiet'+kt_id).modal('hide');
        $('#mdKhenThuongBody #kt_cap_nhat_id').val(kt_id);
        $('#mdKhenThuongBody #kt_ngay_khen_thuong').val(ngay);
        $('#mdKhenThuongBody #kt_thang_khen_thuong').val(thang);
        $('#mdKhenThuongBody #kt_nam_khen_thuong').val(nam);
        $('#mdKhenThuongBody #kt_can_bo').html('<strong>'+em_name+'</strong>');
        tinyMCE.get('kt_chi_tiet').setContent(chi_tiet);
        $('#mdKhenThuongBody #kt_ly_do').val(ly_do);
        $('#mdKhenThuongBody #kt_money').autoNumeric('set',money);
        $('#dv_khen_thuong_success').hide();
        $('#dv_khen_thuong_error').hide();
    }
    
    function postFormKhenThuong(){   
        $.blockUI({
            message: '<h3>Đang thực hiện</h3>',
            css: {                         
                border: 'none', 
                padding: '15px', 
                backgroundColor: '#000', 
                '-webkit-border-radius': '10px', 
                '-moz-border-radius': '10px', 
                opacity: .5, 
                color: '#fff' 
            }
        }); 
        $('#mdKhenThuong').modal('hide');
        $('#dv_khen_thuong_success').hide();
        $('#dv_khen_thuong_error').hide();
        var kt_id = $('#mdKhenThuongBody #kt_cap_nhat_id').val();
        var kt_title = $('#mdKhenThuongBody #kt_ly_do').val();
        var kt_content = tinyMCE.get('kt_chi_tiet').getContent();
        var kt_day = $('#mdKhenThuongBody #kt_ngay_khen_thuong').val();
        var kt_month = $('#mdKhenThuongBody #kt_thang_khen_thuong').val();
        var kt_year = $('#mdKhenThuongBody #kt_nam_khen_thuong').val(); 
        //var kt_money = $('#mdKhenThuongBody #kt_money').val(); 
        var kt_money = $('#mdKhenThuongBody #kt_money').autoNumeric('get');   
        
        if(kt_title !='' && kt_content!=''){
            $.post( site_url+'/tochuccanbo/khenthuong/jqkhenthuong', { 
                kt_id: kt_id, 
                kt_date_day: kt_day, 
                kt_date_month: kt_month,
                kt_date_year: kt_year,
                kt_money: kt_money,
                kt_ly_do: kt_title,
                kt_chi_tiet: kt_content
            }, function( data ) {
                if(data.status){
                    $('#trang_thai_'+kt_id).html('Đã duyệt');
                    $('#mdChiTiet'+kt_id).modal('hide');
                    $.success_ui('Thông báo!', 'Duyệt đơn thành công!', 4000);
                    $('#dv_khen_thuong_success').show();
                    tinyMCE.get('kt_chi_tiet').setContent('');
                    $('#mdKhenThuongBody #kt_ly_do').val('');
                    window.location.reload(true);
                }else{
                    $.error_ui('Thông báo', 'Không thể thực hiện được!', 4000); 
                    $('#dv_khen_thuong_error').show();
                }
            }, 'json');
        }else{
            alert('Bạn phải nhập đầy đủ lý do và nội dung khen thưởng!');
        }
    }
    
    function update_status(id_kt, new_status){
        $('#mdChiTiet'+id_kt).modal('hide');
        $.blockUI({
            message: '<h3>Đang thực hiện</h3>',
            css: {                         
                border: 'none', 
                padding: '15px', 
                backgroundColor: '#000', 
                '-webkit-border-radius': '10px', 
                '-moz-border-radius': '10px', 
                opacity: .5, 
                color: '#fff' 
            }
        }); 
        
        $.post( site_url+'/tochuccanbo/khenthuong/jqupdatestatus', {
            kt_id: id_kt, 
            kt_status: new_status
        }, function(data) {    
            if(data.status){      
                $('#trang_thai_'+id_kt).html(data.new_status);
                $.success_ui('Thông báo!', 'Thực hiện thành công!', 4000);
            }else{
                $.error_ui('Thông báo', 'Không thể thực hiện được!', 4000); 
            }
        }, 'json');
            
    }
</script>
