<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf8" />
        <title></title>
        <style>

            body {
                font-family: "Times New Roman", Times, serif;
            }

            table{
                width: 100%;
                padding:0;
                margin:0 auto;
                border:0;
            }

            table.tb_main{
                width:900px;
            }

            table.tb_border{
                border:1px solid #000;
                border-collapse: separate;
                border-spacing: 0;
            }

            table.tb_border td {
                border: 1px solid #000;
                padding: 2px;
            }

            tr{
                padding:0;
                margin:0;
            }

            td {
                font-family: "Times New Roman", Times, serif;
                padding:0;
                margin:0;
                vertical-align:middle;
                height:30px;
            }

            th {
                font-family: "Times New Roman", Times, serif;
            }

            td.cl_anh{
                border: 1px solid #000;
                width:120px;
                height:180px;
                text-align: center;
                vertical-align: middle;
            }

            .sp_upcase{
                text-transform:uppercase;
            }
        </style>
    </head>

    <body>
        <table class="tb_main">
            <tr>
                <td><p>C&#417;  quan, &#273;&#417;n v&#7883; c&oacute; th&#7849;m quy&#7873;n qu&#7843;n l&yacute; ...................................................................................................................................................................<br />
                        C&#417;  quan, &#273;&#417;n v&#7883; s&#7917; d&#7909;ng CBCC ..............................................................................................................................................................................</p></td>
            </tr>
            <tr>
                <td><p align="center"><strong>S&#416; Y&#7870;U L&Yacute; L&#7882;CH C&Aacute;N B&#7896;, C&Ocirc;NG  CH&#7912;C</strong></p></td>
            </tr>
            <tr>
                <td><table>
                        <tr>
                            <?php
                            $fullname = trim($this->employee_info->em_ho);
                            $fullname .= ' ' . trim($this->employee_info->em_ten);
                            ?>
                            <td  class="cl_anh" width="150" rowspan="5">
                                <?php
                                if ($this->employee_info->em_anh_the) {
                                    echo '<img src="' . UPLOADED_URL . '/avatars/' . $this->employee_info->em_anh_the . '" class="img-polaroid anh_the">';
                                } else {
                                    echo '<img src="' . $this->baseUrl('anh_the.jpg') . '" class="img-polaroid anh_the">';
                                }
                                ?> 
                            </td>
                            <td>1) H&#7885; v&agrave; t&ecirc;n khai sinh: <span class="sp_upcase"><?php echo $fullname; ?></span></td>
                        </tr>
                        <tr>
                            <td>2) T&ecirc;n g&#7885;i kh&aacute;c: <?php echo $this->employee_info->em_ten_khac; ?></td>
                        </tr>
                        <tr>
                            <td><table>
                                    <tr>
                                        <td width="25%">3) Sinh ng&agrave;y: <?php echo ($this->employee_info->em_ngay_sinh ? date('d', strtotime($this->employee_info->em_ngay_sinh)) : ''); ?></td>
                                        <td width="25%">th&aacute;ng: <?php echo ($this->employee_info->em_ngay_sinh ? date('m', strtotime($this->employee_info->em_ngay_sinh)) : ''); ?></td>
                                        <td width="25%">n&#259;m: <?php echo ($this->employee_info->em_ngay_sinh ? date('Y', strtotime($this->employee_info->em_ngay_sinh)) : ''); ?></td>
                                        <td width="25%">Gi&#7899;i t&iacute;nh: <?php echo $this->employee_info->em_gioi_tinh ? 'Nam' : 'Nữ'; ?></td>
                                    </tr>
                                </table></td>
                        </tr>
                        <tr>
                            <td><table>
                                    <tr>
                                        <td width="50%">4) N&#417;i sinh: X&atilde; <?php echo $this->employee_info->em_noi_sinh; ?></td>
                                        <td width="25%"> , Huy&#7879;n: <?php echo $this->employee_info->em_noi_sinh_huyen; ?></td>
                                        <td width="25%">, T&#7881;nh: <?php echo $this->employee_info->em_noi_sinh_tinh; ?></td>
                                    </tr>
                                </table></td>
                        </tr>
                        <tr>
                            <td><table>
                                    <tr>
                                        <td width="50%">5)  Qu&ecirc; qu&aacute;n: X&atilde; <?php echo $this->employee_info->em_que_quan; ?></td>
                                        <td width="25%"> , Huy&#7879;n: <?php echo $this->employee_info->em_que_quan_huyen; ?></td>
                                        <td>, T&#7881;nh: <?php echo $this->employee_info->em_que_quan_tinh; ?></td>
                                    </tr>
                                </table></td>
                        </tr>
                    </table></td>
            </tr>
            <tr>
                <td><table>
                        <tr>
                            <td width="50%">6) D&acirc;n t&#7897;c: <?php echo $this->viewGetDanTocName($this->employee_info->em_dan_toc); ?></td>
                            <td>, 7) T&ocirc;n gi&aacute;o: <?php echo $this->employee_info->em_ton_giao; ?></td>
                        </tr>
                    </table>	</td>
            </tr>
            <tr>
                <td><p>8)  N&#417;i &#273;&#259;ng k&yacute; b&#7897; kh&#7849;u th&#432;&#7901;ng tr&uacute;: <?php echo $this->employee_info->em_dia_chi . ', ' . $this->viewGetHuyenName($this->employee_info->em_dia_chi_huyen) . ', ' . $this->viewGetTinhName($this->employee_info->em_dia_chi_tinh); ?><br />
                        (S&#7889;  nh&agrave;, &#273;&#432;&#7901;ng ph&#7889;, th&agrave;nh ph&#7889;, x&oacute;m, th&ocirc;n, x&atilde;, huy&#7879;n, t&#7881;nh)</p></td>
            </tr>
            <tr>
                <td><p>9)  N&#417;i &#7903; hi&#7879;n nay: <?php echo $this->employee_info->em_noi_o . ', ' . $this->viewGetHuyenName($this->employee_info->em_noi_o_huyen) . ', ' . $this->viewGetTinhName($this->employee_info->em_noi_o_tinh); ?><br />
                        (S&#7889;  nh&agrave;, &#273;&#432;&#7901;ng ph&#7889;, th&agrave;nh ph&#7889;, x&oacute;m, th&ocirc;n, x&atilde;, huy&#7879;n, t&#7881;nh)</p>
                </td>
            </tr>
            <tr>
                <td>10)  Ngh&#7873; nghi&#7879;p khi &#273;&#432;&#7907;c tuy&#7875;n d&#7909;ng: <?php echo $this->employee_info->em_cong_viec_khi_tuyen_dung; ?></td>
            </tr>
            <tr>
                <td>
                    <table>
                        <tr>
                            <td width="40%">11) Ng&agrave;y tuy&#7875;n d&#7909;ng: <?php echo ($this->employee_info->em_ngay_tuyen_dung ? date('d-m-Y', strtotime($this->employee_info->em_ngay_tuyen_dung)) : ''); ?></td>
                            <td>, C&#417; quan tuy&#7875;n d&#7909;ng: <?php echo $this->employee_info->em_co_quan_tuyen_dung; ?></td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td><p>12)  Ch&#7913;c v&#7909; (ch&#7913;c danh) hi&#7879;n t&#7841;i: <?php echo $this->viewGetChucVuName($this->employee_info->em_chuc_vu); ?><br />
                        (V&#7873;  ch&iacute;nh quy&#7873;n ho&#7863;c &#272;&#7843;ng, &#273;o&agrave;n th&#7875;, k&#7875; c&#7843; ch&#7913;c v&#7909; ki&ecirc;m nhi&#7879;m)</p>	</td>
            </tr>
            <tr>
                <td>13)  C&ocirc;ng vi&#7879;c ch&iacute;nh &#273;&#432;&#7907;c giao:	<?php echo $this->employee_info->em_cong_viec; ?></td>
            </tr>
            <tr>
                <td>
                    <table>
                        <tr>
                            <td width="60%">14)  Ng&#7841;ch c&ocirc;ng ch&#7913;c (vi&ecirc;n ch&#7913;c): <?php echo $this->viewGetNgachCongChucName($this->employee_info->em_ngach_cong_chuc); ?></td>
                            <td>, M&atilde; ng&#7841;ch: <?php echo $this->viewGetNgachCongChucMa($this->employee_info->em_ngach_cong_chuc); ?></td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td><table>
                        <tr>
                            <td width="30%">B&#7853;c l&#432;&#417;ng:</td>
                            <td width="30%">H&#7879; s&#7889;:</td>
                            <td>Ng&agrave;y h&#432;&#7903;ng:</td>
                        </tr>
                    </table>	</td>
            </tr>
            <tr>
                <td><table>
                        <tr>
                            <td width="50%">Ph&#7909; c&#7845;p ch&#7913;c v&#7909;:</td>
                            <td>Ph&#7909; c&#7845;p kh&aacute;c:</td>
                        </tr>
                    </table>	</td>
            </tr>
            <tr>
                <td>15.1-  Tr&igrave;nh &#273;&#7897; gi&aacute;o d&#7909;c ph&#7893; th&ocirc;ng (&#273;&atilde; t&#7889;t nghi&#7879;p l&#7899;p m&#7845;y/thu&#7897;c h&#7879; n&agrave;o):	<?php echo $this->employee_info->em_van_hoa_pt; ?></td>
            </tr>
            <tr>
                <td><p>15.2-  Tr&igrave;nh &#273;&#7897; chuy&ecirc;n m&ocirc;n cao nh&#7845;t: <?php echo $this->viewGetHocHamName($this->employee_info->em_hoc_ham); ?><br />
                        (TSKH,  TS, Ths, c&#7917; nh&acirc;n, k&#7929; s&#432;, cao &#273;&#7859;ng, trung c&#7845;p, s&#417; c&#7845;p, chuy&ecirc;n ng&agrave;nh)</p>	
                </td>
            </tr>
            <tr>
                <td><table>
                        <tr>
                            <td width="50%"><p>15.3-  L&yacute; lu&#7853;n ch&iacute;nh tr&#7883;: <?php echo $this->viewGetLyLuanChinhTriName($this->employee_info->em_ly_luan_chinh_tri); ?><br />
                                    (Cao  c&#7845;p, trung c&#7845;p, s&#417; c&#7845;p v&agrave; t&#432;&#417;ng &#273;&#432;&#417;ng)</p></td>
                            <td><p>15.4-Qu&#7843;n  l&yacute; nh&agrave; n&#432;&#7899;c: <?php echo $this->viewGetQuanLyNhaNuocName($this->employee_info->em_quan_ly_nha_nuoc); ?><br />
                                    (chuy&ecirc;n  vi&ecirc;n cao c&#7845;p, chuy&ecirc;n vi&ecirc;n ch&iacute;nh, chuy&ecirc;n vi&ecirc;n, c&aacute;n s&#7921;,........)</p>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td>
                    <table>
                        <tr>
                            <td width="50%"><p>15.5-  Ngo&#7841;i ng&#7919;: <?php echo $this->viewGetChungChiName($this->employee_info->em_ngoai_ngu); ?><br />
                                    (T&ecirc;n  ngo&#7841;i ng&#7919; + Tr&igrave;nh &#273;&#7897; A, B, C, D......)</p></td>
                            <td><p>, 15.6-Tin  h&#7885;c: <?php echo $this->viewGetChungChiName($this->employee_info->em_tin_hoc); ?><br />
                                    (Tr&igrave;nh  &#273;&#7897; A, B, C,.......)</p>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td><table>
                        <tr>
                            <td width="50%">16) Ng&agrave;y v&agrave;o &#273;&#7843;ng: <?php echo ($this->employee_info->em_chuc_vu_dang && $this->employee_info->em_ngay_vao_dang) ? date('d/m/Y', strtotime($this->employee_info->em_ngay_vao_dang)) : ''; ?></td>
                            <td>, Ng&agrave;y ch&iacute;nh th&#7913;c: <?php echo ($this->employee_info->em_chuc_vu_dang && $this->employee_info->em_ngay_vao_dang) ? date('d/m/Y', strtotime($this->employee_info->em_ngay_vao_dang)) : ''; ?></td>
                        </tr>
                    </table></td>
            </tr>
            <tr>
                <td><p>17)  Ng&agrave;y tham gia t&#7893; ch&#7913;c ch&iacute;nh tr&#7883; - x&atilde; h&#7897;i: <?php echo ($this->employee_info->em_chuc_vu_doan && $this->employee_info->em_ngay_vao_doan) ? date('d/m/Y', strtotime($this->employee_info->em_ngay_vao_doan)) : ''; ?> <?php echo $this->employee_info->em_chuc_vu_doan ? ', ' . $this->viewGetChucVuDoanName($this->employee_info->em_chuc_vu_doan) : ''; ?>
                        <br />
                        (Ng&agrave;y  tham gia t&#7893; ch&#7913;c: &#272;o&agrave;n, H&#7897;i,..... v&agrave; l&agrave;m vi&#7879;c g&igrave; trong t&#7893; ch&#7913;c &#273;&oacute;)	</p></td>
            </tr>
            <tr>
                <td><table>
                        <tr>
                            <td><p>18)  Ng&agrave;y nh&#7853;p ng&#361;: <?php echo $this->employee_info->em_ngay_nhap_ngu ? date('d/m/Y', strtotime($this->employee_info->em_ngay_nhap_ngu)) : ''; ?></p></td>
                            <td width="33%"><p>, Ng&agrave;y xu&#7845;t ng&#361;: <?php echo $this->employee_info->em_ngay_xuat_ngu ? date('d-m-Y', strtotime($this->employee_info->em_ngay_xuat_ngu)) : ''; ?></p></td>
                            <td width="33%">, Qu&acirc;n h&agrave;m cao nh&#7845;t: <?php echo $this->employee_info->em_quan_ham; ?></td>
                        </tr>
                    </table>	</td>
            </tr>
            <tr>
                <td><p>19)  Danh hi&#7879;u &#273;&#432;&#7907;c phong t&#7863;ng cao nh&#7845;t: <?php echo $this->employee_info->em_danh_hieu; ?><br />
                        (Anh  h&ugrave;ng lao &#273;&#7897;ng, anh h&ugrave;ng l&#7921;c l&#432;&#7907;ng v&#361; trang; nh&agrave; gi&aacute;o, th&agrave;y thu&#7889;c, ngh&#7879; s&#297; nh&acirc;n  d&acirc;n v&agrave; &#432;u t&uacute;, &hellip;)</p>	</td>
            </tr>
            <tr>
                <td>20)  S&#7903; tr&#432;&#7901;ng c&ocirc;ng t&aacute;c: <?php echo $this->employee_info->em_chuyen_mon; ?></td>
            </tr>
            <tr>
                <td>
                    <table>
                        <tr>
                            <td width="50%"><p>21)  Khen th&#432;&#7903;ng: <?php echo $this->employee_info->em_khen_thuong; ?><br />
                                    (H&igrave;nh  th&#7913;c cao nh&#7845;t, n&#259;m n&agrave;o)</p></td>
                            <td><p>,  22) K&#7927; lu&#7853;t: <?php echo $this->employee_info->em_ky_luat; ?><br />
                                    (v&#7873;  &#273;&#7843;ng, ch&iacute;nh quy&#7873;n, &#273;o&agrave;n th&#7875; h&igrave;nh th&#7913;c cao nh&#7845;t, n&#259;m n&agrave;o)</p>
                            </td>
                        </tr>
                    </table></td>
            </tr>
            <tr>
                <td><table>
                        <tr>
                            <td width="25%">23) T&igrave;nh tr&#7841;ng s&#7913;c kh&#7887;e: <?php echo $this->employee_info->em_tinh_trang_suc_khoe; ?></td>
                            <td width="25%">, Chi&#7873;u cao: <?php echo $this->employee_info->em_chieu_cao ? $this->employee_info->em_chieu_cao . ' cm' : ''; ?> </td>
                            <td width="25%">, C&acirc;n n&#7863;ng: <?php echo $this->employee_info->em_can_nang ? $this->employee_info->em_can_nang . ' kg' : ''; ?></td>
                            <td>, Nh&oacute;m m&aacute;u: <?php echo strtoupper($this->employee_info->em_nhom_mau); ?></td>
                        </tr>
                    </table></td>
            </tr>
            <tr>
                <td><table>
                        <tr>
                            <td width="50%">24)  L&agrave; th&#432;&#417;ng binh h&#7841;ng: <?php echo $this->employee_info->em_thuong_binh; ?></td>
                            <td width="50%">,  L&agrave; con gia &#273;&igrave;nh ch&iacute;nh s&aacute;ch: <?php echo $this->employee_info->em_gia_dinh_chinh_sach; ?></td>
                        </tr>
                    </table></td>
            </tr>
            <tr>
                <td>
                    <table>
                        <tr>
                            <td width="50%">25) S&#7889; ch&#7913;ng minh nh&acirc;n d&acirc;n: <?php echo $this->employee_info->em_so_chung_minh_thu; ?></td>
                            <td width="50%">, Ng&agrave;y c&#7845;p: <?php echo ($this->employee_info->em_cmt_ngay_cap ? date('d-m-Y', strtotime($this->employee_info->em_cmt_ngay_cap)) : ''); ?></td>
                        </tr>
                    </table></td>
            </tr>
            <tr>
                <td>26)  S&#7889; s&#7893; BHXH: <?php echo $this->employee_info->em_so_bhxh; ?></td>
            </tr>
            <tr>
                <td><p>27)  &#272;&agrave;o t&#7841;o, b&#7891;i d&#432;&#7905;ng v&#7873; chuy&ecirc;n m&ocirc;n, nghi&#7879;p v&#7909;, l&yacute; lu&#7853;n ch&iacute;nh tr&#7883;, ngo&#7841;i ng&#7919;, tin  h&#7885;c</p>
                    <table class="tb_border">
                        <tr>
                            <td width="25%"><strong>T&ecirc;n  tr&#432;&#7901;ng</strong></td>
                            <td width="20%"><strong>Chuy&ecirc;n  ng&agrave;nh &#273;&agrave;o t&#7841;o, b&#7891;i d&#432;&#7905;ng</strong></td>
                            <td width="20%"><strong>T&#7915;  th&aacute;ng, n&#259;m - &#273;&#7871;n th&aacute;ng, n&#259;m</strong></td>
                            <td width="15%"><strong>H&igrave;nh  th&#7913;c &#273;&agrave;o t&#7841;o</strong></td>
                            <td width="20%"><strong>V&#259;n  b&#7857;ng, ch&#7913;ng ch&#7881;, tr&igrave;nh &#273;&#7897; g&igrave;</strong></td>
                        </tr>
                        <tr>
                            <?php
                            foreach (unserialize($this->employee_info->em_lich_su_dao_tao) as $item) {
                                echo '<tr>  
                                    <td>' . $item['ten_truong'] . '</td>
                                    <td>' . $item['chuyen_nghanh'] . '</td>
                                    <td>' . $item['ngay_thang'] . '</td>
                                    <td>' . $item['hinh_thuc'] . '</td>
                                    <td>' . $item['van_bang'] . '</td>
                                </tr>';
                            }
                            ?>
                        </tr>
                    </table>

                    <br /><em>Ghi  ch&uacute;: </em>H&igrave;nh th&#7913;c &#273;&agrave;o t&#7841;o: Ch&iacute;nh quy, t&#7841;i ch&#7913;c, chuy&ecirc;n  tu, b&#7891;i d&#432;&#7905;ng ..../ V&#259;n b&#7857;ng: TSKH, TS, Ths, C&#7917; nh&acirc;n, K&#7929; s&#432; ............</td>
            </tr>
            <tr>
                <td>
                    <p>28) T&oacute;m t&#7855;t qu&aacute; tr&igrave;nh c&ocirc;ng t&aacute;c </p>
                    <table class="tb_border">
                        <tr>
                            <td width="40%"><strong>Từ tháng/năm - đến tháng/năm</strong></td>
                            <td width="60%"><strong>Chi tiết</strong></td>
                        </tr>
                        <?php
                        foreach (unserialize($this->employee_info->em_qua_trinh_cong_tac) as $item) {
                            echo '<tr>  
                                    <td>' . $item['ngay_thang'] . '</td>
                                    <td>' . $item['chi_tiet'] . '</td>
                                </tr>';
                        }
                        ?>
                    </table>

                </td>
            </tr>
            <tr>
                <td><p>29) &#272;&#7863;c &#273;i&#7875;m l&#7883;ch s&#7917; b&#7843;n th&acirc;n: <br />
                        - Khai r&otilde;: b&#7883; b&#7855;t, b&#7883; t&ugrave; (t&#7915; ng&agrave;y th&aacute;ng n&#259;m n&agrave;o &#273;&#7871;n ng&agrave;y th&aacute;ng n&#259;m n&agrave;o,  &#7903; &#273;&acirc;u), &#273;&atilde; khai b&aacute;o cho ai, nh&#7919;ng v&#7845;n &#273;&#7873; g&igrave;? B&#7843;n th&acirc;n c&oacute; l&agrave;m vi&#7879;c trong ch&#7871; &#273;&#7897;  c&#361; (c&#417; quan, &#273;&#417;n v&#7883; n&agrave;o, &#273;&#7883;a &#273;i&#7875;m, ch&#7913;c danh, ch&#7913;c v&#7909;, th&#7901;i gian l&agrave;m vi&#7879;c ....)
                        <br />
                        <?php
                        if (trim($this->employee_info->em_bi_bat))
                            echo $this->employee_info->em_bi_bat;
                        else {
                            echo '................................................................................................................................................................................................................................ ';
                            echo '................................................................................................................................................................................................................................ ';
                            echo '................................................................................................................................................................................................................................ ';
                            echo '................................................................................................................................................................................................................................';
                        }
                        ?>
                    </p></td>

            </tr>
            <tr>
                <td><p>- Tham gia ho&#7863;c c&oacute; quan h&#7879; v&#7899;i c&aacute;c t&#7893; ch&#7913;c ch&iacute;nh tr&#7883;, kinh t&#7871;, x&atilde; h&#7897;i  n&agrave;o &#7903; n&#432;&#7899;c ngo&agrave;i (l&agrave;m g&igrave;, t&#7893; ch&#7913;c n&agrave;o, &#273;&#7863;t tr&#7909; s&#7903; &#7903; &#273;&acirc;u .........?): 
                        <br />
                        <?php
                        if (trim($this->employee_info->em_tham_gia_to_chuc))
                            echo $this->employee_info->em_tham_gia_to_chuc;
                        else {
                            echo '................................................................................................................................................................................................................................ ';
                            echo '................................................................................................................................................................................................................................ ';
                            echo '................................................................................................................................................................................................................................ ';
                            echo '................................................................................................................................................................................................................................';
                        }
                        ?>
                    </p></td>
            </tr>
            <tr>
                <td><p>- C&oacute; th&acirc;n nh&acirc;n  (Cha, M&#7865;, V&#7907;, Ch&#7891;ng, con, anh ch&#7883; em ru&#7897;t) &#7903; n&#432;&#7899;c ngo&agrave;i (l&agrave;m g&igrave;, &#273;&#7883;a ch&#7881;)?
                        <br />
                        <?php
                        if (trim($this->employee_info->em_than_nhan_nuoc_ngoai))
                            echo $this->employee_info->em_than_nhan_nuoc_ngoai;
                        else {
                            echo '................................................................................................................................................................................................................................ ';
                            echo '................................................................................................................................................................................................................................ ';
                            echo '................................................................................................................................................................................................................................ ';
                            echo '................................................................................................................................................................................................................................';
                        }
                        ?>
                    </p></td>
            </tr>
            <tr>
                <td><p>30) Quan h&#7879; gia &#273;&igrave;nh<br />
                        a)  V&#7873; b&#7843;n th&acirc;n: Cha, M&#7865;, V&#7907; (ho&#7863;c ch&#7891;ng), c&aacute;c con, anh ch&#7883; em ru&#7897;t</p>
                    <table class="tb_border">
                        <tr>
                            <td style="width: 20%;"><strong>Mối quan hệ</strong></td>
                            <td style="width: 20%;"><strong>Họ và tên</strong></td>
                            <td style="width: 20%;"><strong>Năm sinh</strong></td>
                            <td style="width: 40%;"><strong>Chi tiết</strong></td>
                        </tr>
                        <tr>
                            <?php
                            foreach (unserialize($this->employee_info->em_gia_dinh_ban_than) as $item) {
                                echo '<tr>  
                                    <td>' . $item['moi_quan_he'] . '</td>
                                    <td>' . $item['ho_ten'] . '</td>
                                    <td>' . $item['nam_sinh'] . '</td>
                                    <td>' . $item['chi_tiet'] . '</td>
                                </tr>';
                            }
                            ?>
                        </tr>
                    </table>
                    <p>a)  V&#7873; b&ecirc;n v&#7907; (ho&#7863;c ch&#7891;ng): Cha, M&#7865;, anh ch&#7883; em ru&#7897;t
                    </p>
                    <table class="tb_border">
                        <tr>
                            <td style="width: 20%;"><strong>Mối quan hệ</strong></td>
                            <td style="width: 20%;"><strong>Họ và tên</strong></td>
                            <td style="width: 20%;"><strong>Năm sinh</strong></td>
                            <td style="width: 40%;"><strong>Chi tiết</strong></td>
                        </tr>
                        <tr>
                            <?php
                            foreach (unserialize($this->employee_info->em_gia_dinh_vo) as $item) {
                                echo '<tr>  
                                    <td>' . $item['moi_quan_he'] . '</td>
                                    <td>' . $item['ho_ten'] . '</td>
                                    <td>' . $item['nam_sinh'] . '</td>
                                    <td>' . $item['chi_tiet'] . '</td>
                                </tr>';
                            }
                            ?>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td><p>31) Di&#7877;n bi&#7871;n qu&aacute; tr&igrave;nh l&#432;&#417;ng c&#7911;a c&aacute;n b&#7897;, c&ocirc;ng  ch&#7913;c </p>
                    <?php
                    $td_thang_nam = '';
                    $td_ma_ngach = '';
                    $td_hsl = '';
                    foreach (unserialize($this->employee_info->em_qua_trinh_luong) as $item) {
                        $td_thang_nam .= '<td style="width: 100px;">' . $item['ngay_thang'] . '</td>';
                        $td_ma_ngach .= '<td>' . $item['ma_ngach'] . '</td>';
                        $td_hsl .= '<td>' . $item['he_so'] . '</td>';
                    }
                    $td_thang_nam .= '<td></td>';
                    $td_ma_ngach .= '<td></td>';
                    $td_hsl .= '<td></td>';
                    ?>

                    <table class="tb_border">
                        <tr>
                            <td width="120"><strong>Tháng/năm</strong></td>
                            <?php echo $td_thang_nam; ?>
                        </tr>
                        <tr>
                            <td><strong>Mã ngạch/bậc</strong></td>
                            <?php echo $td_ma_ngach; ?>
                        </tr>
                        <tr>
                            <td><strong>Hệ số lương</strong></td>
                            <?php echo $td_hsl; ?>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td><p>32) Nh&#7853;n x&eacute;t, &#273;&aacute;nh gi&aacute; c&#7911;a c&#417; quan, &#273;&#417;n v&#7883; (ho&#7863;c ch&iacute;nh quy&#7873;n &#273;&#7883;a ph&#432;&#417;ng)
                        <br />
                        <?php
                        echo '................................................................................................................................................................................................................................ ';
                        echo '................................................................................................................................................................................................................................ ';
                        echo '................................................................................................................................................................................................................................ ';
                        echo '................................................................................................................................................................................................................................';
                        ?>
                    </p></td>
            </tr>
            <tr>
                <td><div align="right"><em>...........</em><em>...........</em><em>...........</em><em>.  ng&agrave;y</em><em>...........</em><em> th&aacute;ng</em><em>...........</em><em> n&#259;m........... </em></div></td>
            </tr>
            <tr>
                <td><table>
                        <tr>
                            <td><p align="center"><strong>Ng&#432;&#7901;i  khai</strong><br />
                                    T&ocirc;i  xin cam &#273;oan nh&#7919;ng l&#7901;i khai tr&ecirc;n &#273;&acirc;y l&agrave; &#273;&uacute;ng s&#7921; th&#7853;t <br />
                                    (K&yacute; t&ecirc;n, ghi r&otilde; h&#7885;  t&ecirc;n)</p></td>
                            <td><p align="center"><strong>Th&#7911;  tr&#432;&#7903;ng c&#417; quan, &#273;&#417;n v&#7883; </strong><br />
                                    <strong>(ho&#7863;c  ch&iacute;nh quy&#7873;n &#273;&#7883;a ph&#432;&#417;ng)</strong><br />
                                    <em>(K&yacute;  t&ecirc;n, &#273;&oacute;ng d&#7845;u)</em></p></td>
                        </tr>
                    </table></td>
            </tr>
        </table>
        <script type='application/javascript'>window.onload=function(){window.print()}</script>
    </body>
</html>
