<h5>Quản lý bậc lương</h5>               

<div class="main-content-box">  
    <form name="appForm" method="post" action="">
        <div class="btn-toolbar float_left">
            <div class="btn-group">
                <button class="btn" onclick="OnSubmitForm('<?php echo $this->baseUrl('tochuccanbo/bacluong/deleteitems/'); ?>')"><i class="icon-trash"></i> Xóa chọn</button>
                <a class="btn" href="<?php echo $this->baseUrl('tochuccanbo/bacluong/add'); ?>"><i class="icon-plus-sign"></i> Thêm mới</a>
            </div>
        </div>            
        <div class="clearfix">
        </div>
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th class="checkall_style"><input type="checkbox" name="check_all" id="checkbox" onclick="checkedAll()"></th>
                    <th>Tên bậc lương</th>  
                    <th style="width: 150px;">Sắp xếp</th>
                    <th style="width: 150px;">Trạng thái</th>
                    <th style="width: 150px;">Chức năng</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->list_bac_luong as $item) {
                    echo '<tr>
                            <td class="checkall_style"><input type="checkbox" name="cid[]" id="cid" value="' . $item->bc_id . '"></td>
                            <td><a href="' . $this->baseUrl('tochuccanbo/bacluong/edit/id/' . $item->bc_id) . '">' . $item->bc_name . '</a></td>                            
                            <td class="order_style text-center">' . $item->bc_order . '</td>
                            <td class="status_style"><a href="' . ($item->bc_status ? $this->baseUrl('tochuccanbo/bacluong/changestatus/id/' . $item->bc_id . '/status/0') : $this->baseUrl('tochuccanbo/bacluong/changestatus/id/' . $item->bc_id . '/status/1')) . '"><div class="' . ($item->bc_status ? 'icon_status_active' : 'icon_status_inactive') . '"></div></a></td>
                            <td class="function_style">
                                <a class="btn btn-mini" href="' . $this->baseUrl('tochuccanbo/bacluong/edit/id/' . $item->bc_id) . '" title="Sửa"><i class="icon-edit"></i> Sửa</a>
                                <a class="btn btn-mini" href="' . $this->baseUrl('tochuccanbo/bacluong/delete/id/' . $item->bc_id) . '" title="Xóa"><i class="icon-trash"></i> Xóa</a>                                
                            </td>
                        </tr>';
                }
                ?>
            </tbody>
        </table>
    </form>
</div> 