<h5>Thống kê tháng</h5>               

<div class="main-content-box">  
    <div class="control-group">
        <label class="control-label">Tháng</label>
        <div class="controls">
            <div class="input-append">
                <input class="span2" value="<?php echo $this->thang . '/' . $this->nam; ?>" id="txt_thang_nam" type="text" readonly="true"/>
                <button class="btn" type="button" id="btn_chon_thang">Chọn tháng!</button>
            </div>

        </div>
    </div>
    <div class="clearfix">
    </div>

    <div class="clearfix">
    </div>
    <?php $days_in_month = cal_days_in_month(0, (int) $this->thang, (int) $this->nam); ?>
    <table class="table table-bordered table-hover">
        <thead>
            
            <tr>  
                <th class="checkall_style"  style="vertical-align:inherit" rowspan="2">TT</th>
                <th style="width: 150px;vertical-align:inherit" rowspan="2">Họ tên</th>
                <th colspan="<?php echo $days_in_month ?>" style="text-align: center">Ngày công trong tháng</th>
            </tr>
            <tr>
                <?php for ($i = 1; $i <= $days_in_month; $i++) { ?>
                    <th style="width: 5px;"><?php echo $i ?></th>
                <?php } ?>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->list_nhan_vien as $key => $nv) { ?>
                <?php
                $view_get_chamcong = $this->viewGetChamCong($nv['em_id'], $this->thang, $this->nam);
                ?>
                <tr>
                    <td><?php echo $key ?></td>
                    <td><?php echo $nv['em_ho'] . ' ' . $nv['em_ten_dem'] . ' ' . $nv['em_ten'] ?></td>
                    <?php for ($i = 1; $i <= $days_in_month; $i++) { ?>
                        <?php 
                        $ngay_chamcong = 'c_ngay_' . $i;
                        $trangthai_ngaycong = $view_get_chamcong->$ngay_chamcong;
                        ?>
                        <td style="width: 10px;"><?php echo!empty($this->listHoliday[$trangthai_ngaycong]) ? $this->listHoliday[$trangthai_ngaycong] : '' ?></td>
                    <?php } ?>
                </tr>
            <?php } ?>
        </tbody>
    </table>
    
    <a class="btn btn-small btn-primary" target="_blank" href="<?php echo$this->baseUrl('donvi/thongkethang/pdfthongke/thang/' . $this->thang . '/nam/' . $this->nam); ?>"><i class="icon-download-alt"></i> Xuất ra file PDF</a>
                    <a class="btn btn-small btn-primary" target="_blank" href="<?php echo$this->baseUrl('donvi/thongkethang/exelthongke/thang/' . $this->thang . '/nam/' . $this->nam); ?>"><i class="icon-download-alt"></i> Xuất ra file Exel</a>
</div>



<script>
    var currentYear = <?php echo $this->nam; ?>;
    var options = {
        pattern: 'mm/yyyy', // Default is 'mm/yyyy' and separator char is not mandatory 
        startYear: 2013,
        selectedYear: currentYear,
        monthNames: ['Tháng 1', 'Tháng 2', 'Tháng 3', 'Tháng 4', 'Tháng 5', 'Tháng 6', 'Tháng 7', 'Tháng 8', 'Tháng 9', 'Tháng 10', 'Tháng 11', 'Tháng 12']
    };

    $('#txt_thang_nam').monthpicker(options);

    $('#txt_thang_nam').monthpicker().bind('monthpicker-click-month', function(e, month, year) {
        window.location = site_url + '/donvi/thongkethang/index/thang/' + month + '/nam/' + year;
    });

    $('#btn_chon_thang').bind('click', function() {
        $('#txt_thang_nam').monthpicker('show');
    });
</script>
