<h5>Thống kê tháng</h5>               

<div class="main-content-box">  
    <div class="control-group">
        <label class="control-label">Tháng</label>
        <div class="controls">
            <div class="input-append">
                <input class="span2" value="<?php echo $this->thang . '/' . $this->nam; ?>" id="txt_thang_nam" type="text" readonly="true"/>
                <button class="btn" type="button" id="btn_chon_thang">Chọn tháng!</button>
            </div>

        </div>
    </div>
    <div class="clearfix">
    </div>

    <div class="clearfix">
    </div>
    <?php $days_in_month = cal_days_in_month(0, (int) $this->thang, (int) $this->nam); ?>
    <table class="table table-bordered table-thong-ke-thang">
        <thead>

            <tr>  
                <th style="width: 150px;vertical-align:inherit" rowspan="2">Họ tên</th>
                <th colspan="<?php echo $days_in_month ?>" style="text-align: center">Ngày công trong tháng</th>
                <th style="width: 50px;vertical-align:inherit" colspan="5">Cộng số giờ làm thêm</th>
            </tr>
            <tr>
                <?php for ($i = 1; $i <= $days_in_month; $i++) { ?>                    
                    <th style="width: 5px;" <?php $this->viewCheckChuNhatThuBay($i, (int) $this->thang, (int) $this->nam); ?>><?php echo $i ?></th>
                <?php } ?>
                <th>Số giờ của ngày làm việc</th>
                <th>Số giờ của ngày thứ 7,CN</th>
                <th>Số giờ của ngày lễ tết</th>
                <th>Số giờ làm đêm</th>
                <th>Số giờ nghỉ bù</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($this->list_nhan_vien as $key => $nv) {
                //$ngay_lam_thu_7_cn = 0;
                $so_gio_lam_le_tet = $so_phut_lam_le_tet = 0;
                $so_gio_lam_thu_7_cn = $so_phut_lam_thu_7_cn = 0;
                $view_get_chamcong = $this->viewGetChamCong($nv['em_id'], $this->thang, $this->nam);
                ?>
                <tr>                    
                    <td><?php echo $nv['em_ho'] . ' ' . $nv['em_ten_dem'] . ' ' . $nv['em_ten'] ?></td>
                    <?php for ($i = 1; $i <= $days_in_month; $i++) { ?>
                        <?php
                        $ngay_chamcong = 'c_ngay_' . $i;
                        $trangthai_ngaycong = $view_get_chamcong->$ngay_chamcong;
                        $check_gio_lam_them = $this->viewGetGioLamThem($nv['em_id'], $i, $this->thang, $this->nam);
                        if ($check_gio_lam_them) {
                            if ($this->viewCheckLeTet($i, $this->thang, $this->nam)) {                                
                                $so_gio_lam_le_tet+=$check_gio_lam_them['gio'];
                                $so_phut_lam_le_tet+=$check_gio_lam_them['phut'];
                            } elseif ($this->viewCheckChuNhatThuBay($i, (int) $this->thang, (int) $this->nam)) {
                                $so_gio_lam_thu_7_cn+=$check_gio_lam_them['gio'];
                                $so_phut_lam_thu_7_cn+=$check_gio_lam_them['phut'];
                            }
                        }

                        /* if ($this->viewCheckChuNhatThuBay($i, (int) $this->thang, (int) $this->nam)) {
                          if (!empty($this->listHoliday[$trangthai_ngaycong]) && $this->listHoliday[$trangthai_ngaycong]['ngay_cong'] == 1)
                          $ngay_lam_thu_7_cn++;
                          if (!empty($this->listHoliday[$trangthai_ngaycong]) && $this->listHoliday[$trangthai_ngaycong]['ngay_cong'] == 2)
                          $ngay_lam_thu_7_cn+=0.5;
                          } */
                        ?>
                        <td style="width: 10px;" <?php echo $this->viewCheckChuNhatThuBay($i, (int) $this->thang, (int) $this->nam); ?>><?php echo!empty($this->listHoliday[$trangthai_ngaycong]) ? $this->listHoliday[$trangthai_ngaycong]['code'] : '' ?></td>
                        <?php
                    }
                    
                    $doi_gio_thu_7 = floor($so_phut_lam_thu_7_cn/60);
                    $so_phut_lam_thu_7_cn = $so_phut_lam_thu_7_cn%60;
                    $so_gio_lam_thu_7_cn += $doi_gio_thu_7;
                    
                    $doi_gio_le_tet = floor($so_phut_lam_le_tet/60);
                    $so_phut_lam_le_tet = $so_phut_lam_le_tet%60;
                    $so_gio_lam_le_tet += $doi_gio_le_tet;
                    
                    ?>
                    <td></td>
                    <td><?php echo $so_gio_lam_thu_7_cn.':'.$so_phut_lam_thu_7_cn;?></td>
                    <td><?php echo $so_gio_lam_le_tet.':'.$so_phut_lam_le_tet;?></td>
                    <td></td>
                    <td></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>

    <!--<a class="btn btn-small btn-primary" target="_blank" href="<?php echo$this->baseUrl('donvi/thongkethang/pdfthongke/thang/' . $this->thang . '/nam/' . $this->nam); ?>"><i class="icon-download-alt"></i> Xuất ra file PDF</a>-->
    <a class="btn btn-small btn-primary" target="_blank" href="<?php echo$this->baseUrl('donvi/thongkethang/exelthongke/thang/' . $this->thang . '/nam/' . $this->nam); ?>"><i class="icon-download-alt"></i> Xuất ra file Exel</a>
</div>



<script>
    var currentYear = <?php echo $this->nam; ?>;
    var options = {
        pattern: 'mm/yyyy', // Default is 'mm/yyyy' and separator char is not mandatory 
        startYear: 2013,
        selectedYear: currentYear,
        monthNames: ['Tháng 1', 'Tháng 2', 'Tháng 3', 'Tháng 4', 'Tháng 5', 'Tháng 6', 'Tháng 7', 'Tháng 8', 'Tháng 9', 'Tháng 10', 'Tháng 11', 'Tháng 12']
    };

    $('#txt_thang_nam').monthpicker(options);

    $('#txt_thang_nam').monthpicker().bind('monthpicker-click-month', function(e, month, year) {
        window.location = site_url + '/donvi/thongkethang/index/thang/' + month + '/nam/' + year;
    });

    $('#btn_chon_thang').bind('click', function() {
        $('#txt_thang_nam').monthpicker('show');
    });
</script>
