<div class="body_content float_right">
    <h5>Thành viên</h5>               

    <div class="main-content-box">  
        <form name="appForm" class="form-horizontal" method="post" action="">
            <div class="control-group">
                <label class="control-label">Tháng</label>
                <div class="controls">
                    <div class="input-append">
                        <input class="span2" value="<?php echo $this->thang . '/' . $this->nam; ?>" id="txt_thang_nam" type="text" readonly="true"/>
                        <button class="btn" type="button" id="btn_chon_thang">Chọn tháng!</button>
                    </div>

                </div>
            </div>

            <table class="table table-bordered table-hover">
                <thead>
                    <tr>  
                        <th>Họ tên</th>
                        <th style="width: 90px;">Ngày sinh</th>
                        <th style="width: 90px;">Bắt đầu</th>
                        <th style="width: 90px;">Kết thúc</th>
                        <th style="width: 110px;">Đơn vị</th>
                        <th style="width: 120px;">Phòng tổ chức</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($this->list_nghi_phep as $nghi_phep) {
                        ?>
                        <tr>
                            <td id="name_<?php echo $nghi_phep->xnp_em_id; ?>"><?php echo $nghi_phep->em_ho . ' ' . $nghi_phep->em_ten_dem . ' ' . $nghi_phep->em_ten; ?></td>
                            <td><?php echo date('d-m-Y', strtotime($nghi_phep->em_ngay_sinh)); ?></td>
                            <td><?php echo date('d-m-Y', strtotime($nghi_phep->xnp_from_date)); ?></td>
                            <td><?php echo date('d-m-Y', strtotime($nghi_phep->xnp_to_date)); ?></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <?php
                    }
                    ?>
                </tbody>
            </table>
        </form>
    </div>
</div>



<script>
    var currentYear = <?php echo $this->nam; ?>;    
    var options = {
        pattern: 'mm/yyyy', // Default is 'mm/yyyy' and separator char is not mandatory 
        startYear: 2013,
        selectedYear: currentYear,
        monthNames: ['Tháng 1', 'Tháng 2', 'Tháng 3', 'Tháng 4', 'Tháng 5', 'Tháng 6', 'Tháng 7', 'Tháng 8', 'Tháng 9', 'Tháng 10', 'Tháng 11', 'Tháng 12']
    };

    $('#txt_thang_nam').monthpicker(options);

    $('#txt_thang_nam').monthpicker().bind('monthpicker-click-month', function (e, month, year) { 
        window.location = site_url+'/donvi/duyetnghiphep/index/thang/'+month+'/nam/'+year;
    });

    $('#btn_chon_thang').bind('click', function () {
        $('#txt_thang_nam').monthpicker('show');
    });
</script>
