<div class="body_content float_right">
    <h5>Cập nhật thông tin ngày nghỉ lễ</h5>               

    <div class="main-content-box"> 
        <?php if ($this->error_message) : ?>
            <div class="alert alert-error">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <h5>Thông báo lỗi!</h5>                
                <ol>
                    <?php foreach ($this->error_message as $message): ?>
                        <li><?php echo $message; ?></li>
                    <?php endforeach; ?>
                </ol>
            </div> 
        <?php endif; ?>  
        <?php if ($this->success_message) : ?>
            <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <h5>Thông báo!</h5>
                <?php echo $this->success_message; ?>
            </div>
        <?php endif; ?>  
        <?php if ($this->nn_info) : ?>        
            <form class="form-horizontal" method="post" action="">
                <div class="control-group">
                    <label class="control-label" for="nn_name">Tên ngày nghỉ lễ</label>
                    <div class="controls">
                        <?php echo $this->formText('nn_name', $this->nn_info->nn_name, array('required' => '')); ?>
                        <span class="help-inline">(*)</span>
                    </div>
                </div> 

                <div class="control-group">
                    <label class="control-label" for="nn_tu_ngay">Ngày bắt đầu</label>
                    <div class="controls">
                        <?php echo $this->formText('nn_tu_ngay', date('d/m/Y', strtotime($this->nn_info->nn_tu_ngay)), array('required' => '')); ?>
                        <span class="help-inline">(*)</span>
                    </div>
                </div> 

                <div class="control-group">
                    <label class="control-label" for="nn_den_ngay">Ngày kết thúc</label>
                    <div class="controls">
                        <?php echo $this->formText('nn_den_ngay', date('d/m/Y', strtotime($this->nn_info->nn_den_ngay)), array('required' => '')); ?>
                        <span class="help-inline">(*)</span>
                    </div>
                </div> 

                <div class="control-group">
                    <label class="control-label" for="nn_status">Trạng thái</label>
                    <div class="controls">
                        <?php
                        $status_options = array(1 => 'Sử dụng', 0 => 'Khóa');
                        echo $this->formSelect('nn_status', $this->nn_info->nn_status, null, $status_options);
                        ?>                     
                    </div>
                </div>

                <div class="control-group">
                    <div class="controls">
                        <p>
                            <button class="btn btn-small btn-primary" type="submit">Cập nhật</button>
                            <a class="btn btn-small" type="button" href="<?php echo $this->baseUrl('hethong/nghile/index/page/' . $this->arrParam['page']); ?>">Quay lại</a>
                        </p>
                    </div>
                </div>
            </form>
        <?php else : ?>
            <form class="form-horizontal" method="post" action="">
                <div class="control-group">
                    <div class="controls">
                        <p>
                            <a class="btn btn-small" type="button" href="<?php echo $this->baseUrl('hethong/nghile/index/page/' . $this->arrParam['page']); ?>">Quay lại</a>
                        </p>
                    </div>
                </div>
            </form>
        <?php endif; ?>        
    </div> 
</div>