<h5>Thống kê tháng</h5>               

<div class="main-content-box">  
    <form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
        <div class="control-group">
            <label class="control-label">Tháng</label>
            <div class="controls">
                <div class="input-append">
                    <input class="span2" value="<?php echo $this->thang . '/' . $this->nam; ?>" id="txt_thang_nam" type="text" readonly="true"/>
                    <button class="btn" type="button" id="btn_chon_thang">Chọn tháng!</button>
                </div>
                <?php
                if ($this->cham_cong && ($this->cham_cong->c_don_vi_status != '-1' || $this->cham_cong->c_ptccb_status != '-1')) {
                    echo '<span class="help-block">Tháng này đã được phê duyệt.</span>';
                }
                ?>

            </div>
        </div>
        <?php
        $holiday_options = array('' => '');
        foreach ($this->list_holidays as $holiday) {
            $holiday_options["$holiday->hld_id"] = $holiday->hld_name;
        }


//This gets today's date
        $date = time();

//This puts the day, month, and year in seperate variables
        $day = date('d', $date);
        $month = $this->thang;
        $year = $this->nam;

//Here we generate the first day of the month
        $first_day = mktime(0, 0, 0, $month, 1, $year);

//This gets us the month name
        $title = date('m', $first_day);

//Here we find out what day of the week the first day of the month falls on
        $day_of_week = date('D', $first_day);

//Once we know what day of the week it falls on, we know how many blank days occure before it. If the first day of the week is a Sunday then it would be zero
        switch ($day_of_week) {
            case "Sun": $blank = 0;
                break;
            case "Mon": $blank = 1;
                break;
            case "Tue": $blank = 2;
                break;
            case "Wed": $blank = 3;
                break;
            case "Thu": $blank = 4;
                break;
            case "Fri": $blank = 5;
                break;
            case "Sat": $blank = 6;
                break;
        }

//We then determine how many days are in the current month
        $days_in_month = cal_days_in_month(0, $month, $year);
//Here we start building the table heads
        $txt_duyet_status = '(Chưa được duyệt)';
        if ($this->cham_cong && ($this->cham_cong->c_don_vi_status != '-1' || $this->cham_cong->c_ptccb_status != '-1')) {
            $txt_duyet_status = '(Đã được duyệt)';
        }
        echo "<table class='table table-bordered'>";
        echo "<tr><th colspan=7> Chấm công $txt_duyet_status</th></tr>";
        echo "<tr>
            <td width='102' class='error'>Chủ nhật</td>
            <td width='102'>Thứ 2</td>
            <td width='102'>Thứ 3</td>
            <td width='102'>Thứ 4</td>
            <td width='102'>Thứ 5</td>
            <td width='102'>Thứ 6</td>
            <td width='102' class='warning'>Thứ 7</td></tr>";

//This counts the days in the week, up to 7
        $day_count = 1;

        echo "<tr>";
//first we take care of those blank days
        while ($blank > 0) {
            echo "<td></td>";
            $blank = $blank - 1;
            $day_count++;
        }

//sets the first day of the month to 1
        $day_num = 1;

//count up the days, untill we've done all of them in the month
        while ($day_num <= $days_in_month) {
            $class_name = '';
            switch ($day_count) {
                case 1:
                    $class_name = 'error';
                    break;
                case 7:
                    $class_name = 'warning';
                    break;
            }
            $ngay_hom_nay = $year . '-' . $month . '-' . $day_num;
            $du_lieu_da_chon = null;
            if ($this->cham_cong) {
                eval('$du_lieu_da_chon = $this->cham_cong->c_ngay_' . $day_num . ';');
            }
            $text_show = "<td class='$class_name'>
                <div class='row-fluid'>$day_num</div>
                <div class='row-fluid'>$holiday_options[$du_lieu_da_chon]</div>
            </td>";
            ;
            foreach ($this->list_nghi_phep as $item) {
                $ngay_so_sanh_1 = date('y-m-d', strtotime($item->xnp_from_date));
                $ngay_so_sanh_2 = date('y-m-d', strtotime($item->xnp_to_date));
                if (strtotime($ngay_hom_nay) >= strtotime($ngay_so_sanh_1) && strtotime($ngay_hom_nay) <= strtotime($ngay_so_sanh_2)) {
                    $text_show = "<td class='$class_name'>
                        <div class='row-fluid'>$day_num</div>
                        <div class='row-fluid'>" . $item->xnp_ly_do . "</div>
                    </td>";
                    break;
                }
            }
            echo $text_show;
            $day_num++;
            $day_count++;

//Make sure we start a new row every week
            if ($day_count > 7) {
                echo "</tr><tr>";
                $day_count = 1;
            }
        }
//Finaly we finish out the table with some blank details if needed
        while ($day_count > 1 && $day_count <= 7) {
            echo "<td> </td>";
            $day_count++;
        }

        echo "</tr></table>";
        ?>

        <h5>Khen thưởng</h5>  

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th style="width: 15px;">#</th>
                    <th style="width: 90px;">Ngày</th>
                    <th style="width: 250px;">Lý do</th>
                    <th>Chi tiết</th>
                    <th style="width: 120px;">Mức thưởng</th>
                </tr>
            </thead>
            <tbody>
                <?php
                if (sizeof($this->khen_thuong)) {
                    $i = 0;
                    foreach ($this->khen_thuong as $khen_thuong) {
                        $i++;
                        echo "<tr>
                            <td>$i</td>
                            <td>" . date('d-m-Y', strtotime($khen_thuong->kt_date)) . "</td>
                            <td>$khen_thuong->kt_ly_do</td>
                            <td>$khen_thuong->kt_chi_tiet</td>
                            <td>$khen_thuong->kt_money VND</td>
                        </tr>";
                    }
                } else {
                    echo '<tr><td colspan="5">Không có khen thưởng nào!</td></tr>';
                }
                ?>                
            </tbody>
        </table>

        <h5>Kỷ luật/khiển trách</h5>  

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th style="width: 15px;">#</th>
                    <th style="width: 90px;">Ngày</th>
                    <th style="width: 250px;">Lý do</th>
                    <th>Chi tiết</th>
                    <th style="width: 120px;">Mức phạt</th>
                </tr>
            </thead>
            <tbody>
                <?php
                if (sizeof($this->ky_luat)) {
                    $i = 0;
                    foreach ($this->ky_luat as $ky_luat) {
                        $i++;
                        echo "<tr>
                            <td>$i</td>
                            <td>" . date('d-m-Y', strtotime($ky_luat->kl_date)) . "</td>
                            <td>$ky_luat->kl_ly_do</td>
                            <td>$ky_luat->kl_chi_tiet</td>
                            <td>$ky_luat->kl_money VND</td>
                        </tr>";
                    }
                } else {
                    echo '<tr><td colspan="5">Không có kỷ luật/khiển trách nào!</td></tr>';
                }
                ?>                
            </tbody>
        </table>
    </form>
</div> 

<script>
    var currentYear = <?php echo $this->nam; ?>;    
    var options = {
        pattern: 'mm/yyyy', // Default is 'mm/yyyy' and separator char is not mandatory 
        startYear: 2013,
        selectedYear: currentYear,
        monthNames: ['Tháng 1', 'Tháng 2', 'Tháng 3', 'Tháng 4', 'Tháng 5', 'Tháng 6', 'Tháng 7', 'Tháng 8', 'Tháng 9', 'Tháng 10', 'Tháng 11', 'Tháng 12']
    };

    $('#txt_thang_nam').monthpicker(options);

    $('#txt_thang_nam').monthpicker().bind('monthpicker-click-month', function (e, month, year) { 
        window.location = site_url+'/canhan/thongkethang/index/thang/'+month+'/nam/'+year;
    });

    $('#btn_chon_thang').bind('click', function () {
        $('#txt_thang_nam').monthpicker('show');
    });
</script>