<?php 
echo $this->blkFrontInfo(); 
echo $this->blkFrontThongBao(); 
?>


<h5>Liên kết nhanh</h5>               

<div class="main-content-box">                     
    <p>
        <button class="btn btn-small" type="button"><i class="icon-list-alt"></i> Thông báo</button>
        <button class="btn btn-small" type="button"><i class="icon-hand-up"></i> Chấm công</button>
        <button class="btn btn-small" type="button"><i class="icon-time"></i> Khai báo làm ngoài giờ</button>
        <button class="btn btn-small" type="button"><i class="icon-flag"></i> Xin nghỉ phép</button>
        <button class="btn btn-small" type="button"><i class="icon-hand-up"></i> Chấm công</button>
        <button class="btn btn-small" type="button"><i class="icon-hand-up"></i> Chấm công</button>
    </p>
</div>