<?php 
echo $this->blkFrontInfo(); 
echo $this->blkFrontThongBao(); 
?>


<h5>Liên kết nhanh</h5>               

<div class="main-content-box">                     
    <p>
        <a class="btn btn-small" href="<?php echo $this->baseUrl('canhan/thongbao');?>"><i class="icon-list-alt"></i> Thông báo</a>
        <a class="btn btn-small" href="<?php echo $this->baseUrl('canhan/chamcong');?>"><i class="icon-hand-up"></i> Chấm công</a>
        <a class="btn btn-small" href="<?php echo $this->baseUrl('canhan/khaibaothemgio');?>"><i class="icon-time"></i> Khai báo làm ngoài giờ</a>
        <a class="btn btn-small" href="<?php echo $this->baseUrl('canhan/xinnghiphep');?>"><i class="icon-flag"></i> Xin nghỉ phép</a>
        <a class="btn btn-small" href="<?php echo $this->baseUrl('canhan/thongkethang');?>"><i class="icon-hand-up"></i> Thống kê</a>
        <a class="btn btn-small" href="<?php echo $this->baseUrl('canhan/danhgiaphanloai');?>"><i class="icon-hand-up"></i> Tự đánh giá</a>
    </p>
</div>