<div class="body_content float_right">
    <h5>Khai báo làm thêm giờ</h5>               

    <div class="main-content-box">  
        <?php if ($this->error_message) : ?>
            <div class="alert alert-error">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <h5>Thông báo!</h5>
                Thêm mới không thành công vì:
                <ol>
                    <?php foreach ($this->error_message as $message): ?>
                        <li><?php echo $message; ?></li>
                    <?php endforeach; ?>
                </ol>
            </div> 
        <?php endif; ?>  
        <?php if ($this->success_message) : ?>
            <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <h5>Thông báo!</h5>
                <?php echo $this->success_message; ?>
            </div>
        <?php endif; ?> 
        <form class="form-horizontal" method="post" action="">
            <div class="control-group">
                <label class="control-label" for="ltg_date">Ngày</label>
                <div class="controls">
                    <?php echo $this->formText('ltg_date', $this->arrParam['ltg_date'], array('class' => 'input-large', 'placeholder' => '')); ?>                  
                    <span class="help-block">Chọn ngày làm thêm giờ</span>
                </div>            
            </div>
            <?php
            $gio_sang_options = array(''=>'');
            for ($h = 7; $h <= 11; $h++) {
                $gio_sang_options[$h] = $h;
            }
            
            $gio_chieu_options = array('' => '');
            for ($h = 14; $h <= 17; $h++) {
                $gio_chieu_options[$h] = $h;
            }
            
            $phut_options = array();
            for ($m = 0; $m <= 59; $m+=5) {
                $phut_options[$m] = $m;
            }
            ?>
            <div class="control-group">
                <label class="control-label" for="ltg_gio_bat_dau">Giờ làm sáng</label>
                <div class="controls">
                    <div class="input-prepend input-append">
                        <span class="add-on">giờ</span>
                        <?php
                        echo $this->formSelect('ltg_gio_bat_dau', $this->arrParam['ltg_gio_bat_dau'], array('class' => 'input-mini'), $gio_sang_options);
                        ?>                        
                    </div>
                    <div class="input-prepend input-append">
                        <span class="add-on">phút</span>
                        <?php
                        echo $this->formSelect('ltg_phut_bat_dau', $this->arrParam['ltg_phut_bat_dau'], array('class' => 'input-mini'), $phut_options);
                        ?>                        
                    </div> 
                     - 
                    <div class="input-prepend input-append">
                        <span class="add-on">giờ</span>
                        <?php
                        echo $this->formSelect('ltg_gio_ket_thuc', $this->arrParam['ltg_gio_ket_thuc'], array('class' => 'input-mini'), $gio_sang_options);
                        ?>                        
                    </div>
                    <div class="input-prepend input-append">
                        <span class="add-on">phút</span>
                        <?php
                        echo $this->formSelect('ltg_phut_ket_thuc', $this->arrParam['ltg_phut_ket_thuc'], array('class' => 'input-mini'), $phut_options);
                        ?>                        
                    </div> 

                </div>            
            </div>
            <div class="control-group">
                <label class="control-label" for="ltg_gio_bat_dau_chieu">Giờ làm chiều</label>
                <div class="controls">
                    <div class="input-prepend input-append">
                        <span class="add-on">giờ</span>
                        <?php
                        echo $this->formSelect('ltg_gio_bat_dau_chieu', $this->arrParam['ltg_gio_bat_dau_chieu'], array('class' => 'input-mini'), $gio_chieu_options);
                        ?>                        
                    </div>
                    <div class="input-prepend input-append">
                        <span class="add-on">phút</span>
                        <?php
                        echo $this->formSelect('ltg_phut_bat_dau_chieu', $this->arrParam['ltg_phut_bat_dau_chieu'], array('class' => 'input-mini'), $phut_options);
                        ?>                        
                    </div> 
                     - 
                    <div class="input-prepend input-append">
                        <span class="add-on">giờ</span>
                        <?php
                        echo $this->formSelect('ltg_gio_ket_thuc_chieu', $this->arrParam['ltg_gio_ket_thuc_chieu'], array('class' => 'input-mini'), $gio_chieu_options);
                        ?>                        
                    </div>
                    <div class="input-prepend input-append">
                        <span class="add-on">phút</span>
                        <?php
                        echo $this->formSelect('ltg_phut_ket_thuc_chieu', $this->arrParam['ltg_phut_ket_thuc_chieu'], array('class' => 'input-mini'), $phut_options);
                        ?>                        
                    </div>             

                </div>            
            </div>

            <div class="control-group">
                <label class="control-label" for="ltg_chi_tiet">Chi tiết</label>
                <div class="controls">
                    <?php echo $this->formTextarea('ltg_chi_tiet', $this->arrParam['ltg_chi_tiet'], array('class' => 'input-xlarge', 'rows' => 10)); ?>                   
                </div>            
            </div>

            <div class="control-group">
                <div class="controls">
                    <p>
                        <button class="btn btn-small btn-primary" type="submit">Đồng ý</button>
                        <a class="btn btn-small" type="button" href="<?php echo $this->baseUrl('canhan/khaibaothemgio/index/page/' . $this->arrParam['page']); ?>">Quay lại</a>
                    </p>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    $(function() {
        $( "#ltg_date" ).datepicker({
            yearRange: '1900:2050',
            changeMonth: true,
            changeYear: true,
            defaultDate: "+1w",
            numberOfMonths: 1,
            dateFormat: 'd/m/yy',
            showOn: "button",
            buttonImage: site_url+"/date-picker-icon.png",
            buttonImageOnly: true
        });
        
        $.validator.addMethod('vietnameeseDate',
        function (value, element) {
            if (this.optional(element)) {
                return true;
            }
            var ok = true;
            try {
                $.datepicker.parseDate('dd/mm/yy', value);
            }
            catch (err) {
                ok = false;
            }
            return ok;
        });
        $('form').validate({
            onKeyup : true,            
            rules: {            
                // compound rule
                ltg_date: {
                    required: true, 
                    vietnameeseDate: true
                }
            },
            highlight: function(element) {
                $(element).closest('div.control-group').removeClass('success').addClass('error');
            },
            success: function(element) {
                $(element).closest('div.control-group').removeClass('error').addClass('success');
            }
        });
    });
</script>
