
<h5>Cập nhật bậc lương</h5>               

<div class="main-content-box"> 
    <?php if ($this->error_message) : ?>
        <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h5>Thông báo!</h5>
            Thêm mới không thành công vì:
            <ol>
                <?php foreach ($this->error_message as $message): ?>
                    <li><?php echo $message; ?></li>
                <?php endforeach; ?>
            </ol>
        </div> 
    <?php endif; ?>  
    <?php if ($this->success_message) : ?>
        <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h5>Thông báo!</h5>
            <?php echo $this->success_message; ?>
        </div>
    <?php endif; ?>  
    <form class="form-horizontal" method="post" action="">
        <div class="control-group">
            <label class="control-label" for="bl_name">Tên bậc lương</label>
            <div class="controls">
                <?php echo $this->formText('bl_name', $this->bl_info->bl_name, array('required' => '')); ?>
                <span class="help-inline">(*)</span>
            </div>
        </div> 

        <?php
        $he_so_luong = unserialize($this->bl_info->bl_he_so_luong);
        foreach ($this->list_ngach as $ngach_cong_chuc) {
            ?>

            <div class="control-group">
                <label class="control-label"><?php echo $ngach_cong_chuc->ncc_name; ?></label>
                <div class="controls">                
                    <div class="input-prepend input-append">    
                        <?php
                        echo $this->formText('bl_he_so_luong[' . $ngach_cong_chuc->ncc_id . ']', $he_so_luong[$ngach_cong_chuc->ncc_id], array('class' => 'input-medium', 'placeholder' => '', 'required' => ''));
                        ?>    
                        <span class="add-on">Hệ số</span>     
                    </div>    
                </div>            
            </div> 

        <?php } ?>

        <div class="control-group">
            <label class="control-label" for="bl_order">Vị trí</label>
            <div class="controls">
                <?php echo $this->formText('bl_order', $this->bl_info->bl_order, array()); ?>
                <span class="help-block">Dùng để sắp xếp vị trí hiển thị khi dùng.</span>
            </div>                
        </div>

        <div class="control-group">
            <label class="control-label" for="bl_status">Trạng thái</label>
            <div class="controls">
                <?php
                $status_options = array(1 => 'Sử dụng', 0 => 'Khóa');
                echo $this->formSelect('bl_status', $this->bl_info->bl_status, null, $status_options);
                ?>                     
            </div>
        </div> 
        <div class="control-group">
            <div class="controls">
                <p>
                    <button class="btn btn-small btn-primary" type="submit">Cập nhật</button>
                    <a class="btn btn-small" type="button" href="<?php echo $this->baseUrl('tochuccanbo/bacluong/index'); ?>">Quay lại</a>
                </p>
            </div>
        </div>
    </form>
</div> 