<div class="body_content float_right">
    <h5>Thêm tên đánh giá kết quả công việc mới</h5>               

    <div class="main-content-box"> 
        <?php if ($this->error_message) : ?>
            <div class="alert alert-error">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <h5>Thông báo!</h5>
                Thêm mới không thành công vì:
                <ol>
                    <?php foreach ($this->error_message as $message): ?>
                        <li><?php echo $message; ?></li>
                    <?php endforeach; ?>
                </ol>
            </div> 
        <?php endif; ?>  
        <?php if ($this->success_message) : ?>
            <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <h5>Thông báo!</h5>
                <?php echo $this->success_message; ?>
            </div>
        <?php endif; ?>  
        <form class="form-horizontal" method="post" action="">
            <div class="control-group">
                <label class="control-label" for="dgkqcv_name">Tên đánh giá kết quả công việc</label>
                <div class="controls">
                    <?php echo $this->formText('dgkqcv_name', NULL, array('required' => '')); ?>
                    <span class="help-inline">(*)</span>
                </div>
            </div> 
            
            <div class="control-group">
                <label class="control-label" for="dgkqcv_order">Vị trí</label>
                <div class="controls">
                    <?php echo $this->formText('dgkqcv_order', NULL, array()); ?>
                    <span class="help-block">Dùng để sắp xếp vị trí hiển thị khi dùng.</span>
                </div>                
            </div>
            
            <div class="control-group">
                <label class="control-label" for="dgkqcv_status">Trạng thái</label>
                <div class="controls">
                    <?php
                    $status_options = array(1=>'Sử dụng', 0=>'Khóa');                    
                    echo $this->formSelect('dgkqcv_status', null, null, $status_options);
                    ?>                     
                </div>
            </div> 
            <div class="control-group">
                <div class="controls">
                    <p>
                        <button class="btn btn-small btn-primary" type="submit">Thêm mới</button>
                        <a class="btn btn-small" type="button" href="<?php echo $this->baseUrl('hethong/ketqua/index/page/'.$this->arrParam['page']); ?>">Quay lại</a>
                    </p>
                </div>
            </div>
        </form>
    </div> 
</div>