<div class="body_content float_right">
    <h5>Cập nhật thông tin chứng chỉ</h5>               

    <div class="main-content-box"> 
        <?php if ($this->error_message) : ?>
            <div class="alert alert-error">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <h5>Thông báo lỗi!</h5>                
                <ol>
                    <?php foreach ($this->error_message as $message): ?>
                        <li><?php echo $message; ?></li>
                    <?php endforeach; ?>
                </ol>
            </div> 
        <?php endif; ?>  
        <?php if ($this->success_message) : ?>
            <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <h5>Thông báo!</h5>
                <?php echo $this->success_message; ?>
            </div>
        <?php endif; ?>  
        <?php if ($this->cc_info) : ?>        
            <form class="form-horizontal" method="post" action="">
                <div class="control-group">
                    <label class="control-label" for="cc_name">Tên chứng chỉ</label>
                    <div class="controls">
                        <?php echo $this->formText('cc_name', $this->cc_info->cc_name, array('required' => '')); ?>
                        <span class="help-inline">(*)</span>
                    </div>
                </div> 

                <div class="control-group">
                    <label class="control-label" for="cc_type">Loại chứng chỉ</label>
                    <div class="controls">
                        <?php
                        $type_options = array(1 => 'Ngoại ngữ', 2 => 'Tin học', 0=> 'Loại khác');
                        echo $this->formSelect('cc_type', $this->cc_info->cc_type, null, $type_options);
                        ?>                     
                    </div>
                </div>
                
                <div class="control-group">
                    <label class="control-label" for="cc_order">Vị trí</label>
                    <div class="controls">
                        <?php echo $this->formText('cc_order', $this->cc_info->cc_order, array()); ?>
                        <span class="help-block">Dùng để sắp xếp vị trí hiển thị khi dùng.</span>
                    </div>                
                </div>

                <div class="control-group">
                    <label class="control-label" for="cc_status">Trạng thái</label>
                    <div class="controls">
                        <?php
                        $status_options = array(1 => 'Sử dụng', 0 => 'Khóa');
                        echo $this->formSelect('cc_status', $this->cc_info->cc_status, null, $status_options);
                        ?>                     
                    </div>
                </div>
                <div class="control-group">
                    <div class="controls">
                        <p>
                            <button class="btn btn-small btn-primary" type="submit">Cập nhật</button>
                            <a class="btn btn-small" type="button" href="<?php echo $this->baseUrl('hethong/chungchi/index/page/' . $this->arrParam['page']); ?>">Quay lại</a>
                        </p>
                    </div>
                </div>
            </form>
        <?php else : ?>
            <form class="form-horizontal" method="post" action="">
                <div class="control-group">
                    <div class="controls">
                        <p>
                            <a class="btn btn-small" type="button" href="<?php echo $this->baseUrl('hethong/chungchi/index/page/' . $this->arrParam['page']); ?>">Quay lại</a>
                        </p>
                    </div>
                </div>
            </form>
        <?php endif; ?>        
    </div> 
</div>